import { bibliographicCoupling, clampGraphExpansion, normalizeContributor, stableKnowledgeEdgeId, stableKnowledgeNodeId, weightedTopicOverlap, type GraphExpansionOptions, type KnowledgeEdge, type KnowledgeNode, type OpenAlexResolution, type OpenAlexWork } from '@seshat/core';
import type { CatalogGraphEdgeInput, CatalogGraphNodeInput, CatalogPaperRecord, PostgresCatalog } from './index.js';

const generatedAt=()=>new Date().toISOString(); const algorithmVersion='scholarly-v1';
const paperNodeId=(paper:CatalogPaperRecord)=>paper.openAlexId?stableKnowledgeNodeId('paper',paper.openAlexId):`paper:local:${paper.referenceId}`;
const workFrom=(paper:CatalogPaperRecord):OpenAlexWork|undefined=>paper.openAlexWork as unknown as OpenAlexWork|undefined;
const asGraphInput=(nodes:KnowledgeNode[],edges:KnowledgeEdge[]):{nodes:CatalogGraphNodeInput[];edges:CatalogGraphEdgeInput[]}=>({nodes:nodes.map((node)=>({key:node.id,kind:node.kind,label:node.label,properties:{...node.properties,classification:node.kind,pipeline:algorithmVersion}})),edges:edges.map((edge)=>({key:edge.id,from:edge.source,to:edge.target,relation:edge.kind,weight:edge.weight,properties:{directed:edge.directed,evidence:edge.evidence,provenance:{...edge.provenance,pipeline:algorithmVersion}}}))});

export const metadataFromOpenAlex=(work:OpenAlexWork)=>({title:work.title,contributors:work.authors.map((author)=>normalizeContributor(author.name,{inferSimpleNames:true})).filter(Boolean),issued:work.publicationYear?{year:work.publicationYear}:undefined,doi:work.doi,abstract:work.abstract,publisher:work.venue?.name,url:`https://openalex.org/${work.id}`});

export async function rebuildScholarlyGraph(catalog:PostgresCatalog,ownerKey:string,topicThreshold=.25):Promise<void>{
  const papers=await catalog.listPapers(ownerKey); const resolved=papers.filter((paper)=>paper.resolutionStatus==='resolved'&&workFrom(paper)); const libraries=await catalog.pool.query(`SELECT item.reference_id,library.id,library.name FROM catalog_library_items item JOIN catalog_libraries library ON library.id=item.library_id WHERE library.owner_key=$1`,[ownerKey]); const collections=new Map<string,Array<{id:string;name:string}>>();libraries.rows.forEach((row:any)=>collections.set(row.reference_id,[...(collections.get(row.reference_id)||[]),{id:row.id,name:row.name}]));
  for(const paper of papers){const work=workFrom(paper);const nodes:KnowledgeNode[]=[];const edges:KnowledgeEdge[]=[];const root=paperNodeId(paper);nodes.push({id:root,kind:'paper',label:work?.title||paper.title,properties:{referenceId:paper.referenceId,openAlexId:paper.openAlexId,doi:paper.doi,resolutionStatus:paper.resolutionStatus,citedByCount:work?.citedByCount||0,radius:Math.max(6,Math.min(22,6+2*Math.log1p(work?.citedByCount||0)))}});
    for(const collection of collections.get(paper.referenceId)||[]){const collectionId=`collection:${collection.id}`;nodes.push({id:collectionId,kind:'collection',label:collection.name,properties:{libraryId:collection.id}});edges.push({id:stableKnowledgeEdgeId('belongs-to-collection',root,collectionId,true),source:root,target:collectionId,kind:'belongs-to-collection',directed:true,weight:1,evidence:{method:'catalog-library-membership'},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});}
    if(work){for(const author of work.authors){const authorId=stableKnowledgeNodeId('author',author.id);nodes.push({id:authorId,kind:'author',label:author.name,properties:{openAlexId:author.id}});edges.push({id:stableKnowledgeEdgeId('authored-by',root,authorId,true),source:root,target:authorId,kind:'authored-by',directed:true,weight:1,evidence:{method:'openalex-authorship'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});for(const institutionId of author.institutionIds){const institution=work.institutions.find((candidate)=>candidate.id===institutionId);if(!institution)continue;const nodeId=stableKnowledgeNodeId('institution',institution.id);nodes.push({id:nodeId,kind:'institution',label:institution.name,properties:{openAlexId:institution.id}});edges.push({id:stableKnowledgeEdgeId('affiliated-with',authorId,nodeId,true),source:authorId,target:nodeId,kind:'affiliated-with',directed:true,weight:1,evidence:{method:'openalex-authorship-institution'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}}for(const topic of work.topics){const topicId=stableKnowledgeNodeId('topic',topic.id);nodes.push({id:topicId,kind:'topic',label:topic.name,properties:{openAlexId:topic.id,score:topic.score,field:topic.field}});edges.push({id:stableKnowledgeEdgeId('has-topic',root,topicId,true),source:root,target:topicId,kind:'has-topic',directed:true,weight:topic.score,evidence:{method:'openalex-topic-score'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}if(work.venue){const venueId=stableKnowledgeNodeId('venue',work.venue.id);nodes.push({id:venueId,kind:'venue',label:work.venue.name,properties:{openAlexId:work.venue.id}});edges.push({id:stableKnowledgeEdgeId('published-in',root,venueId,true),source:root,target:venueId,kind:'published-in',directed:true,weight:1,evidence:{method:'openalex-primary-location'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}for(const referenceId of work.referencedWorkIds){const target=stableKnowledgeNodeId('paper',referenceId);const expanded=(paper.expansion as any)?.referenceWorks?.find?.((item:any)=>item.id===referenceId);nodes.push({id:target,kind:'paper',label:expanded?.title||referenceId,properties:{openAlexId:referenceId,external:!resolved.some((candidate)=>candidate.openAlexId===referenceId),citedByCount:expanded?.citedByCount||0}});edges.push({id:stableKnowledgeEdgeId('cites',root,target,true),source:root,target,kind:'cites',directed:true,weight:1,evidence:{method:'openalex-referenced-works',count:1},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}}
    for(const other of resolved){if(other.referenceId===paper.referenceId)continue;const otherWork=workFrom(other)!;const target=paperNodeId(other);nodes.push({id:target,kind:'paper',label:otherWork.title,properties:{referenceId:other.referenceId,openAlexId:other.openAlexId,citedByCount:otherWork.citedByCount}});if(!work)continue;const coupling=bibliographicCoupling(work.referencedWorkIds,otherWork.referencedWorkIds);if(coupling.sharedCount>=2)edges.push({id:stableKnowledgeEdgeId('bibliographic-coupling',root,target),source:root,target,kind:'bibliographic-coupling',directed:false,weight:coupling.score,evidence:{method:'cosine-reference-overlap',count:coupling.sharedCount,sharedIds:coupling.sharedIds,description:`${coupling.sharedCount} shared references`},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});const authors=work.authors.map((item)=>item.id).filter((id)=>otherWork.authors.some((item)=>item.id===id)).sort();if(authors.length)edges.push({id:stableKnowledgeEdgeId('shared-author',root,target),source:root,target,kind:'shared-author',directed:false,weight:authors.length,evidence:{method:'openalex-author-id-overlap',count:authors.length,sharedIds:authors},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});const topics=weightedTopicOverlap(work.topics,otherWork.topics);if(topics.score>=topicThreshold)edges.push({id:stableKnowledgeEdgeId('shared-topic',root,target),source:root,target,kind:'shared-topic',directed:false,weight:topics.score,evidence:{method:'weighted-jaccard',count:topics.sharedIds.length,sharedIds:topics.sharedIds},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});const citingA=new Set(((paper.expansion as any)?.citingWorks||[]).map((item:any)=>item.id)),citingB=new Set(((other.expansion as any)?.citingWorks||[]).map((item:any)=>item.id));const sharedCiting=[...citingA].filter((id)=>citingB.has(id)).sort() as string[];if(sharedCiting.length)edges.push({id:stableKnowledgeEdgeId('co-citation',root,target),source:root,target,kind:'co-citation',directed:false,weight:sharedCiting.length,evidence:{method:'bounded-local-citing-work-overlap',count:sharedCiting.length,sharedIds:sharedCiting},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});}
    const graph=asGraphInput(nodes,edges);await catalog.replaceGraphForReferencePipeline(ownerKey,paper.referenceId,algorithmVersion,graph.nodes,graph.edges);
  }
}

export async function persistResolution(catalog:PostgresCatalog,ownerKey:string,referenceId:string,resolution:OpenAlexResolution,expansion:Partial<GraphExpansionOptions>={},client?:{worksByIds(ids:string[],limit?:number):Promise<OpenAlexWork[]>;citingWorks(id:string,limit?:number):Promise<OpenAlexWork[]>}):Promise<CatalogPaperRecord|null>{const options=clampGraphExpansion(expansion);const work=resolution.work;let referenceWorks:OpenAlexWork[]=[];let citingWorks:OpenAlexWork[]=[];if(work&&client&&options.citationDepth===1){if(options.includeReferences)referenceWorks=await client.worksByIds(work.referencedWorkIds,options.maxReferencesPerPaper);if(options.includeCitingWorks)citingWorks=await client.citingWorks(work.id,options.maxCitingWorksPerPaper);}const saved=await catalog.savePaperResolution(ownerKey,referenceId,{status:resolution.status,method:resolution.method,confidence:resolution.confidence,candidates:resolution.candidates,work:work as any,expansion:{options,referenceWorks,citingWorks},provenance:{resolution:{source:'openalex',retrievedAt:generatedAt(),method:resolution.method,confidence:resolution.confidence}},metadata:work?metadataFromOpenAlex(work):undefined});if(saved)await rebuildScholarlyGraph(catalog,ownerKey);return saved;}
