import { bibliographicCoupling, clampGraphExpansion, deduplicateKnowledgeGraph, normalizeContributor, normalizeDoi, normalizeScholarlyTitle, stableKnowledgeEdgeId, stableKnowledgeNodeId, weightedTopicOverlap, type GraphExpansionOptions, type KnowledgeEdge, type KnowledgeNode, type OpenAlexResolution, type OpenAlexWork } from '@seshat/core';
import type { CatalogGraphEdgeInput, CatalogGraphNodeInput, CatalogPaperRecord, PostgresCatalog } from './index.js';

const generatedAt=()=>new Date().toISOString(); const algorithmVersion='scholarly-v1';
const paperNodeId=(paper:CatalogPaperRecord)=>paper.openAlexId?stableKnowledgeNodeId('paper',paper.openAlexId):`paper:local:${paper.referenceId}`;
const workFrom=(paper:CatalogPaperRecord):OpenAlexWork|undefined=>paper.openAlexWork as unknown as OpenAlexWork|undefined;
const asGraphInput=(nodes:KnowledgeNode[],edges:KnowledgeEdge[]):{nodes:CatalogGraphNodeInput[];edges:CatalogGraphEdgeInput[]}=>{const graph=deduplicateKnowledgeGraph(nodes,edges);return {nodes:graph.nodes.map((node)=>({key:node.id,kind:node.kind,label:node.label,properties:{...node.properties,classification:node.kind,pipeline:algorithmVersion}})),edges:graph.edges.map((edge)=>({key:edge.id,from:edge.source,to:edge.target,relation:edge.kind,weight:edge.weight,properties:{directed:edge.directed,evidence:edge.evidence,provenance:{...edge.provenance,pipeline:algorithmVersion}}}))};};

export const metadataFromOpenAlex=(work:OpenAlexWork)=>({title:work.title,contributors:work.authors.map((author)=>normalizeContributor(author.name,{inferSimpleNames:true})).filter(Boolean),issued:work.publicationYear?{year:work.publicationYear}:undefined,doi:work.doi,abstract:work.abstract,publisher:work.venue?.name,url:`https://openalex.org/${work.id}`});

type ExtractedReferenceLike={raw?:unknown;title?:unknown;authors?:unknown;year?:unknown;doi?:unknown;confidence?:unknown};
type ScholarlyExpansion={referenceWorks?:OpenAlexWork[];citingWorks?:OpenAlexWork[];relatedWorks?:OpenAlexWork[]};
const paperDoi=(paper:CatalogPaperRecord)=>normalizeDoi(paper.doi||workFrom(paper)?.doi||'');
const paperYear=(paper:CatalogPaperRecord)=>Number((paper.extractedMetadata as {publicationYear?:unknown})?.publicationYear||workFrom(paper)?.publicationYear)||undefined;
const paperTitle=(paper:CatalogPaperRecord)=>normalizeScholarlyTitle(workFrom(paper)?.title||paper.title||paper.normalizedTitle);
const workGraphProperties=(work?:OpenAlexWork)=>work?{year:work.publicationYear,authors:work.authors.map((author)=>author.name),abstract:work.abstract}:{};

export function buildBibliographyConnections(paper:CatalogPaperRecord,papers:CatalogPaperRecord[]):{nodes:KnowledgeNode[];edges:KnowledgeEdge[]}{
  const nodes:KnowledgeNode[]=[];const edges:KnowledgeEdge[]=[];const root=paperNodeId(paper);const work=workFrom(paper);
  const expansion=paper.expansion as ScholarlyExpansion;const openAlexReferences=new Set(work?.referencedWorkIds||[]);const expanded=Array.isArray(expansion.referenceWorks)?expansion.referenceWorks:[];
  for(const rawReference of Array.isArray(paper.extractedReferences)?paper.extractedReferences:[]){
    const reference=(rawReference||{}) as ExtractedReferenceLike;const doi=normalizeDoi(String(reference.doi||''));const normalizedTitle=normalizeScholarlyTitle(reference.title||'');const year=Number(reference.year)||undefined;
    if(!doi&&!normalizedTitle)continue;
    const expandedWork=expanded.find((candidate)=>Boolean(doi&&normalizeDoi(candidate.doi||'')===doi)||Boolean(normalizedTitle&&normalizeScholarlyTitle(candidate.title)===normalizedTitle));
    const local=papers.find((candidate)=>candidate.referenceId!==paper.referenceId&&(Boolean(doi&&paperDoi(candidate)===doi)||Boolean(normalizedTitle&&paperTitle(candidate)===normalizedTitle&&(!year||!paperYear(candidate)||paperYear(candidate)===year))));
    const targetWork=expandedWork||(local?workFrom(local):undefined);const target=local?paperNodeId(local):targetWork?stableKnowledgeNodeId('paper',targetWork.id):stableKnowledgeNodeId('paper',doi||`${normalizedTitle}:${year||''}`);
    if(target===root||Boolean(targetWork&&openAlexReferences.has(targetWork.id)))continue;
    const label=targetWork?.title||local?.title||String(reference.title||reference.raw||doi).trim().slice(0,280);if(!label)continue;
    nodes.push({id:target,kind:'paper',label,properties:{referenceId:local?.referenceId,openAlexId:targetWork?.id,doi:doi||targetWork?.doi,...workGraphProperties(targetWork),year:year||targetWork?.publicationYear,authors:targetWork?.authors.map((author)=>author.name)||reference.authors,external:!local,bibliographyDerived:true}});
    const confidence=Math.max(.1,Math.min(1,Number(reference.confidence)||.35));
    edges.push({id:stableKnowledgeEdgeId('cites',root,target,true),source:root,target,kind:'cites',directed:true,weight:confidence,evidence:{method:'extracted-bibliography',count:1,description:'Citation parsed from the document bibliography'},provenance:{source:'local-extraction',generatedAt:generatedAt(),algorithmVersion}});
  }
  return {nodes,edges};
}

export async function rebuildScholarlyGraph(catalog:PostgresCatalog,ownerKey:string,topicThreshold=.25):Promise<void>{
  const papers=await catalog.listPapers(ownerKey); const resolved=papers.filter((paper)=>paper.resolutionStatus==='resolved'&&workFrom(paper)); const libraries=await catalog.pool.query(`SELECT item.reference_id,library.id,library.name FROM catalog_library_items item JOIN catalog_libraries library ON library.id=item.library_id WHERE library.owner_key=$1`,[ownerKey]); const collections=new Map<string,Array<{id:string;name:string}>>();libraries.rows.forEach((row:any)=>collections.set(row.reference_id,[...(collections.get(row.reference_id)||[]),{id:row.id,name:row.name}]));
  for(const paper of papers){const work=workFrom(paper);const nodes:KnowledgeNode[]=[];const edges:KnowledgeEdge[]=[];const root=paperNodeId(paper);nodes.push({id:root,kind:'paper',label:work?.title||paper.title,properties:{referenceId:paper.referenceId,openAlexId:paper.openAlexId,doi:paper.doi,...workGraphProperties(work),resolutionStatus:paper.resolutionStatus,citedByCount:work?.citedByCount||0,referenceCount:Math.max(paper.extractedReferences.length,work?.referencedWorkIds.length||0),radius:Math.max(6,Math.min(22,6+2*Math.log1p(work?.citedByCount||0)))}});
    for(const collection of collections.get(paper.referenceId)||[]){const collectionId=`collection:${collection.id}`;nodes.push({id:collectionId,kind:'collection',label:collection.name,properties:{libraryId:collection.id}});edges.push({id:stableKnowledgeEdgeId('belongs-to-collection',root,collectionId,true),source:root,target:collectionId,kind:'belongs-to-collection',directed:true,weight:1,evidence:{method:'catalog-library-membership'},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});}
    const bibliography=buildBibliographyConnections(paper,papers);nodes.push(...bibliography.nodes);edges.push(...bibliography.edges);
    if(work){for(const author of work.authors){const authorId=stableKnowledgeNodeId('author',author.id);nodes.push({id:authorId,kind:'author',label:author.name,properties:{openAlexId:author.id}});edges.push({id:stableKnowledgeEdgeId('authored-by',root,authorId,true),source:root,target:authorId,kind:'authored-by',directed:true,weight:1,evidence:{method:'openalex-authorship'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});for(const institutionId of author.institutionIds){const institution=work.institutions.find((candidate)=>candidate.id===institutionId);if(!institution)continue;const nodeId=stableKnowledgeNodeId('institution',institution.id);nodes.push({id:nodeId,kind:'institution',label:institution.name,properties:{openAlexId:institution.id}});edges.push({id:stableKnowledgeEdgeId('affiliated-with',authorId,nodeId,true),source:authorId,target:nodeId,kind:'affiliated-with',directed:true,weight:1,evidence:{method:'openalex-authorship-institution'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}}for(const topic of work.topics){const topicId=stableKnowledgeNodeId('topic',topic.id);nodes.push({id:topicId,kind:'topic',label:topic.name,properties:{openAlexId:topic.id,score:topic.score,field:topic.field}});edges.push({id:stableKnowledgeEdgeId('has-topic',root,topicId,true),source:root,target:topicId,kind:'has-topic',directed:true,weight:topic.score,evidence:{method:'openalex-topic-score'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}if(work.venue){const venueId=stableKnowledgeNodeId('venue',work.venue.id);nodes.push({id:venueId,kind:'venue',label:work.venue.name,properties:{openAlexId:work.venue.id}});edges.push({id:stableKnowledgeEdgeId('published-in',root,venueId,true),source:root,target:venueId,kind:'published-in',directed:true,weight:1,evidence:{method:'openalex-primary-location'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}for(const referenceId of work.referencedWorkIds){const target=stableKnowledgeNodeId('paper',referenceId);const expanded=(paper.expansion as any)?.referenceWorks?.find?.((item:any)=>item.id===referenceId);const local=resolved.find((candidate)=>candidate.openAlexId===referenceId);const label=expanded?.title||(local?workFrom(local)?.title:undefined);if(!label)continue;nodes.push({id:target,kind:'paper',label,properties:{referenceId:local?.referenceId,openAlexId:referenceId,external:!local,citedByCount:expanded?.citedByCount||(local?workFrom(local)?.citedByCount:0)||0,referenceCount:expanded?.referencedWorkIds?.length||(local?workFrom(local)?.referencedWorkIds.length:0)||0}});edges.push({id:stableKnowledgeEdgeId('cites',root,target,true),source:root,target,kind:'cites',directed:true,weight:1,evidence:{method:'openalex-referenced-works',count:1},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}}
    for(const other of resolved){if(other.referenceId===paper.referenceId)continue;const otherWork=workFrom(other)!;const target=paperNodeId(other);nodes.push({id:target,kind:'paper',label:otherWork.title,properties:{referenceId:other.referenceId,openAlexId:other.openAlexId,citedByCount:otherWork.citedByCount}});if(!work)continue;const coupling=bibliographicCoupling(work.referencedWorkIds,otherWork.referencedWorkIds);if(coupling.sharedCount>=2)edges.push({id:stableKnowledgeEdgeId('bibliographic-coupling',root,target),source:root,target,kind:'bibliographic-coupling',directed:false,weight:coupling.score,evidence:{method:'cosine-reference-overlap',count:coupling.sharedCount,sharedIds:coupling.sharedIds,description:`${coupling.sharedCount} shared references`},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});const authors=work.authors.map((item)=>item.id).filter((id)=>otherWork.authors.some((item)=>item.id===id)).sort();if(authors.length)edges.push({id:stableKnowledgeEdgeId('shared-author',root,target),source:root,target,kind:'shared-author',directed:false,weight:authors.length,evidence:{method:'openalex-author-id-overlap',count:authors.length,sharedIds:authors},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});const topics=weightedTopicOverlap(work.topics,otherWork.topics);if(topics.score>=topicThreshold)edges.push({id:stableKnowledgeEdgeId('shared-topic',root,target),source:root,target,kind:'shared-topic',directed:false,weight:topics.score,evidence:{method:'weighted-jaccard',count:topics.sharedIds.length,sharedIds:topics.sharedIds},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});const citingA=new Set(((paper.expansion as any)?.citingWorks||[]).map((item:any)=>item.id)),citingB=new Set(((other.expansion as any)?.citingWorks||[]).map((item:any)=>item.id));const sharedCiting=[...citingA].filter((id)=>citingB.has(id)).sort() as string[];if(sharedCiting.length)edges.push({id:stableKnowledgeEdgeId('co-citation',root,target),source:root,target,kind:'co-citation',directed:false,weight:sharedCiting.length,evidence:{method:'bounded-local-citing-work-overlap',count:sharedCiting.length,sharedIds:sharedCiting},provenance:{source:'derived',generatedAt:generatedAt(),algorithmVersion}});}
    if(work){const expandedRelated=(paper.expansion as ScholarlyExpansion).relatedWorks||[];for(const relatedId of work.relatedWorkIds||[]){const related=expandedRelated.find((candidate)=>candidate.id===relatedId);const local=resolved.find((candidate)=>candidate.openAlexId===relatedId);const label=related?.title||(local?workFrom(local)?.title:undefined);if(!label)continue;const target=local?paperNodeId(local):stableKnowledgeNodeId('paper',relatedId);if(target===root)continue;nodes.push({id:target,kind:'paper',label,properties:{referenceId:local?.referenceId,openAlexId:relatedId,external:!local,citedByCount:related?.citedByCount||(local?workFrom(local)?.citedByCount:0)||0}});edges.push({id:stableKnowledgeEdgeId('related-to',root,target),source:root,target,kind:'related-to',directed:false,weight:1,evidence:{method:'openalex-related-works',count:1,description:'Suggested by OpenAlex as a related work'},provenance:{source:'openalex',generatedAt:generatedAt(),algorithmVersion}});}}
    const workIndex=new Map<string,OpenAlexWork>();for(const candidate of papers){const candidateWork=workFrom(candidate);if(candidateWork)workIndex.set(candidateWork.id,candidateWork);}for(const candidate of [...((paper.expansion as ScholarlyExpansion).referenceWorks||[]),...((paper.expansion as ScholarlyExpansion).relatedWorks||[]),...((paper.expansion as ScholarlyExpansion).citingWorks||[])])workIndex.set(candidate.id,candidate);for(const node of nodes){if(node.kind!=='paper')continue;const openAlexId=String(node.properties?.openAlexId||'');const nodeWork=workIndex.get(openAlexId);if(nodeWork)node.properties={...(node.properties||{}),...workGraphProperties(nodeWork)};}
    const graph=asGraphInput(nodes,edges);await catalog.replaceGraphForReferencePipeline(ownerKey,paper.referenceId,algorithmVersion,graph.nodes,graph.edges);
  }
}

export async function persistResolution(catalog:PostgresCatalog,ownerKey:string,referenceId:string,resolution:OpenAlexResolution,expansion:Partial<GraphExpansionOptions>={},client?:{worksByIds(ids:string[],limit?:number):Promise<OpenAlexWork[]>;citingWorks(id:string,limit?:number):Promise<OpenAlexWork[]>}):Promise<CatalogPaperRecord|null>{
  const options=clampGraphExpansion(expansion);const work=resolution.work;let referenceWorks:OpenAlexWork[]=[];let citingWorks:OpenAlexWork[]=[];let relatedWorks:OpenAlexWork[]=[];
  if(work&&client){
    if(options.citationDepth===1&&options.includeReferences)referenceWorks=await client.worksByIds(work.referencedWorkIds,options.maxReferencesPerPaper);
    if(options.citationDepth===1&&options.includeCitingWorks)citingWorks=await client.citingWorks(work.id,options.maxCitingWorksPerPaper);
    if(options.maxRelatedPapers>0)relatedWorks=await client.worksByIds(work.relatedWorkIds,options.maxRelatedPapers);
  }
  const saved=await catalog.savePaperResolution(ownerKey,referenceId,{status:resolution.status,method:resolution.method,confidence:resolution.confidence,candidates:resolution.candidates,work:work as any,expansion:{options,referenceWorks,citingWorks,relatedWorks},provenance:{resolution:{source:'openalex',retrievedAt:generatedAt(),method:resolution.method,confidence:resolution.confidence}},metadata:work?metadataFromOpenAlex(work):undefined});if(saved)await rebuildScholarlyGraph(catalog,ownerKey);return saved;
}
