import { browserSpeech } from './browser-speech';

type ReaderEngine = 'native' | 'kokoro';
type ReaderState = 'idle' | 'loading' | 'reading' | 'paused';
type Sentence = { raw:string; text:string; start:number; end:number };
type ReaderMount = { referenceId:string; language:string; container:HTMLElement; button:HTMLButtonElement; stopButton?:HTMLButtonElement; report:(message:string,tone?:'ready'|'saving'|'error')=>void };

const SETTINGS_KEY='seshat.read-aloud.v1';
const MODEL_ID='onnx-community/Kokoro-82M-v1.0-ONNX';
export const KOKORO_VOICES=[
  {id:'ef_dora',label:'Dora · español · local'},
  {id:'em_alex',label:'Alex · español · local'},
  {id:'em_santa',label:'Santa · español · local'},
  {id:'af_heart',label:'Heart · English · local'},
  {id:'af_bella',label:'Bella · English · local'},
  {id:'am_michael',label:'Michael · English · local'},
];

type ReaderSettings={engine:ReaderEngine;voice:string;rate:number;nativeVoices:string[]};
const readSettings=():ReaderSettings=>{try{return{engine:'native',voice:'',rate:1,nativeVoices:[],...JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')}}catch{return{engine:'native',voice:'',rate:1,nativeVoices:[]}}};
export const normalizeReaderLanguage=(value:string)=>{const normalized=String(value||'').trim().toLowerCase();const aliases:Record<string,string>={spa:'es',spanish:'es','español':'es',castellano:'es',eng:'en',english:'en','inglés':'en',fra:'fr',fre:'fr',french:'fr','français':'fr',deu:'de',ger:'de',german:'de','alemán':'de',ita:'it',italian:'it',por:'pt',portuguese:'pt',cat:'ca',catalan:'ca',nld:'nl',dut:'nl',dutch:'nl',lat:'la',latin:'la'};if(aliases[normalized])return aliases[normalized];try{return new Intl.Locale(normalized.replace('_','-')).language.toLowerCase();}catch{return normalized.slice(0,2);}};
const languageCode=normalizeReaderLanguage;
const cleanSpeech=(value:string)=>value
  .replace(/^---[\s\S]*?---\s*/,'').replace(/```[\s\S]*?```/g,' ')
  .replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1')
  .replace(/https?:\/\/\S+/g,' ').replace(/^\s{0,3}(?:#{1,6}|>|[-*+]\s|\d+[.)]\s)/gm,'')
  .replace(/[*_`~]/g,'').replace(/\s+/g,' ').trim();

const wavBlob=(parts:Float32Array[],sampleRate:number)=>{const samples=parts.reduce((sum,item)=>sum+item.length,0);const buffer=new ArrayBuffer(44+samples*2);const view=new DataView(buffer);const text=(offset:number,value:string)=>{for(let index=0;index<value.length;index+=1)view.setUint8(offset+index,value.charCodeAt(index));};text(0,'RIFF');view.setUint32(4,36+samples*2,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,samples*2,true);let offset=44;for(const part of parts)for(const sample of part){const clipped=Math.max(-1,Math.min(1,sample));view.setInt16(offset,clipped<0?clipped*0x8000:clipped*0x7fff,true);offset+=2;}return new Blob([buffer],{type:'audio/wav'});};

export const splitReadingSentences=(source:string,language='en'):Sentence[]=>{
  const segments:Array<{segment:string;index:number}>=[];
  try{const Segmenter=(Intl as any).Segmenter;const segmenter=new Segmenter(language||'en',{granularity:'sentence'});for(const value of segmenter.segment(source))segments.push({segment:value.segment,index:value.index});}
  catch{let cursor=0;for(const segment of source.match(/[^.!?\n]+(?:[.!?]+|\n+|$)/g)||[]){const index=source.indexOf(segment,cursor);segments.push({segment,index});cursor=index+segment.length;}}
  return segments.map(({segment,index})=>({raw:segment,text:cleanSpeech(segment),start:index,end:index+segment.length})).filter((item)=>item.text.length>1&&item.text.length<1800);
};

class ReadAloudController{
  state:ReaderState='idle';activeEngine:ReaderEngine|null=null;mount:ReaderMount|null=null;sentences:Sentence[]=[];index=0;current:Sentence|null=null;token=0;audio:HTMLAudioElement|null=null;audioContext:AudioContext|null=null;audioSources=new Set<AudioBufferSourceNode>();audioTimeline:Array<{start:number;end:number;sentence:Sentence;index:number}>=[];audioTimelineTimer=0;scheduledUntil=0;source='';dialog:HTMLDialogElement|null=null;kokoro:any=null;voiceData=new Map<string,Float32Array>();
  constructor(){if(typeof document==='undefined')return;document.addEventListener('keydown',(event)=>{const target=event.target as HTMLElement|null;if(target?.matches('input,textarea,select,[contenteditable="true"]')||event.metaKey||event.ctrlKey||event.altKey)return;if(event.key.toLowerCase()==='m'&&this.current&&this.state!=='idle'){event.preventDefault();void this.mark();}});}
  attach(mount:ReaderMount){if(this.mount&&this.mount.referenceId!==mount.referenceId&&this.state!=='idle')this.stop();this.mount=mount;let timer=0,long=false;const open=(event?:Event)=>{event?.preventDefault();long=true;this.openVoices();};const down=(event:PointerEvent)=>{if(event.pointerType==='mouse')return;long=false;timer=window.setTimeout(()=>open(event),560);};const clear=()=>{window.clearTimeout(timer);};mount.button.addEventListener('pointerdown',down);mount.button.addEventListener('pointerup',clear);mount.button.addEventListener('pointercancel',clear);mount.button.addEventListener('pointermove',clear);mount.button.addEventListener('click',(event)=>{if(long){long=false;return;}this.mount=mount;if(event.shiftKey){this.openVoices();return;}void this.toggle();});mount.stopButton?.addEventListener('click',()=>{this.mount=mount;this.stop();mount.report('reading stopped');});mount.button.title='Read aloud · Shift-click or long press for voices · M marks the current sentence';this.paintButton();return()=>{clear();if(this.mount?.button===mount.button&&this.state==='idle')this.mount=null;};}
  paintButton(){if(!this.mount)return;const labels:Record<ReaderState,string>={idle:'Read',loading:'Loading…',reading:'Pause',paused:'Resume'};this.mount.button.textContent=labels[this.state];this.mount.button.dataset.readerState=this.state;if(this.mount.stopButton)this.mount.stopButton.hidden=this.state==='idle';}
  async toggle(){if(!this.mount||this.state==='loading')return;if(this.state==='reading'){this.pause();return;}if(this.state==='paused'){this.resume();return;}await this.start();}
  async loadText(){if(!this.mount)return;const response=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/artifact/markdown`,{cache:'no-store'});if(!response.ok)throw new Error('Extracted text is required before reading aloud.');this.source=await response.text();this.sentences=splitReadingSentences(this.source,this.mount.language);if(!this.sentences.length)throw new Error('No readable sentences were found.');this.index=0;const annotations=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/annotations`).then((result)=>result.ok?result.json():null).catch(()=>null);const mark=(annotations?.annotations||[]).filter((item:any)=>item.noteType==='reading-mark').sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];if(mark){const next=this.sentences.findIndex((sentence)=>sentence.start>=Number(mark.endOffset||0));if(next>=0)this.index=next;}}
  async start(){if(!this.mount)return;if(this.state!=='idle')this.stop(false);const settings=readSettings();this.activeEngine=settings.engine;this.state='loading';this.paintButton();this.mount.report('preparing read aloud…','saving');try{await this.loadText();const token=++this.token;if(settings.engine==='kokoro')await this.runKokoro(token);else await this.runNative(token);}catch(error){this.activeEngine=null;this.state='idle';this.paintButton();this.mount?.report(error instanceof Error?error.message:'Read aloud failed','error');}}
  pause(){if(this.state!=='reading')return;this.state='paused';if(this.activeEngine==='native')browserSpeech.pause();else{this.audio?.pause();void this.audioContext?.suspend();}this.paintButton();}
  resume(){if(this.state!=='paused')return;this.state='reading';if(this.activeEngine==='native')browserSpeech.resume();else{void this.audio?.play();void this.audioContext?.resume();}this.paintButton();}
  stop(clear=true){this.token+=1;if(this.activeEngine==='native')browserSpeech.stop();else{this.audio?.pause();if(this.audio)this.audio.src='';this.audio=null;window.clearInterval(this.audioTimelineTimer);this.audioTimelineTimer=0;this.audioSources.forEach((source)=>{try{source.stop();}catch{}});this.audioSources.clear();this.audioTimeline=[];this.scheduledUntil=0;if(this.audioContext){void this.audioContext.close();this.audioContext=null;}}this.activeEngine=null;this.clearHighlight();this.current=null;this.state='idle';if(clear)this.paintButton();}
  async speakNative(sentence:Sentence,voice:SpeechSynthesisVoice,language:string,rate:number,token:number){await browserSpeech.speak({text:sentence.text,voice,language,rate,isCurrent:()=>token===this.token,onStart:()=>{this.showSentence(sentence);this.mount?.report(`speaking · ${voice.name} · ${voice.lang}`,'saving');}});}
  async runNative(token:number){if(!('speechSynthesis'in window))throw new Error('SpeechSynthesis is not available.');const settings=readSettings();const voices=await this.nativeVoices();const language=this.mount?.language||navigator.language;const code=normalizeReaderLanguage(language);const allowed=settings.nativeVoices.length?voices.filter((item)=>settings.nativeVoices.includes(item.name)):voices;const preferred=voices.find((item)=>item.name===settings.voice);const preferredForLanguage=preferred&&allowed.includes(preferred)&&normalizeReaderLanguage(preferred.lang)===code?preferred:null;const voice=preferredForLanguage||allowed.filter((item)=>normalizeReaderLanguage(item.lang)===code).sort((a,b)=>Number(/Microsoft.*Natural/i.test(b.name))-Number(/Microsoft.*Natural/i.test(a.name)))[0]||(preferred&&allowed.includes(preferred)?preferred:null)||allowed[0]||preferred||voices[0];if(!voice)throw new Error('No browser voices are installed.');this.mount?.report(`queued · ${voice.name} · ${voice.lang}`,'saving');this.state='reading';this.paintButton();for(;this.index<this.sentences.length&&token===this.token;this.index+=1){const sentence=this.sentences[this.index];await this.speakNative(sentence,voice,language,settings.rate,token);}if(token===this.token)this.finish();}
  async nativeVoices(){return browserSpeech.voices();}
  async loadKokoro(){if(this.kokoro)return this.kokoro;this.mount?.report('downloading Kokoro local model · first use ≈95 MB','saving');const [{KokoroTTS},{env}]=await Promise.all([import('kokoro-js'),import('@huggingface/transformers')]);const wasm=env.backends.onnx.wasm as any;wasm.wasmPaths=undefined;wasm.proxy=true;wasm.numThreads=1;this.kokoro=await KokoroTTS.from_pretrained(MODEL_ID,{dtype:'q8',device:'wasm',progress_callback:(progress:any)=>{if(progress?.status==='progress'&&Number.isFinite(progress.progress))this.mount?.report(`loading Kokoro · ${Math.round(progress.progress)}%`,'saving');}});return this.kokoro;}
  async kokoroAudio(sentence:string,voice:string,rate:number){const tts=await this.loadKokoro();if(!voice.startsWith('e'))return tts.generate(sentence,{voice:voice as any,speed:rate});const [{phonemizeSpanish},{Tensor,RawAudio}]=await Promise.all([import('./spanish-phonemizer'),import('@huggingface/transformers')]);const phonemes=await phonemizeSpanish(sentence);const {input_ids}=tts.tokenizer(phonemes,{truncation:true});let voices=this.voiceData.get(voice);if(!voices){const url=`https://huggingface.co/${MODEL_ID}/resolve/main/voices/${voice}.bin`;const response=await fetch(url);if(!response.ok)throw new Error(`Voice ${voice} could not be downloaded.`);voices=new Float32Array(await response.arrayBuffer());this.voiceData.set(voice,voices);}const offset=256*Math.min(Math.max(Number(input_ids.dims.at(-1))-2,0),509);const style=voices.slice(offset,offset+256);const {waveform}=await tts.model({input_ids,style:new Tensor('float32',style,[1,256]),speed:new Tensor('float32',[rate],[1])});return new RawAudio(waveform.data as Float32Array,24000);}
  async renderNarration(referenceId:string,language:string,voice:string,report:(message:string)=>void){if(this.state!=='idle')this.stop();const response=await fetch(`/api/library/${encodeURIComponent(referenceId)}/artifact/markdown`,{cache:'no-store'});if(!response.ok)throw new Error('Extracted text is required before rendering narration.');const source=await response.text();const sentences=splitReadingSentences(source,language);if(!sentences.length)throw new Error('No readable sentences were found.');const code=languageCode(language||navigator.language);const selected=KOKORO_VOICES.some((item)=>item.id===voice)?voice:code==='es'?'ef_dora':'af_heart';const cleared=await fetch(`/api/library/${encodeURIComponent(referenceId)}/narration`,{method:'DELETE'});if(!cleared.ok)throw new Error('Existing narration could not be cleared.');let cursor=0,segment=0,parts:Float32Array[]=[],sampleRate=24000,samples=0;const upload=async()=>{if(!parts.length)return;report(`Kokoro · uploading segment ${segment+1}`);const result=await fetch(`/api/library/${encodeURIComponent(referenceId)}/narration?voice=${encodeURIComponent(selected)}&language=${encodeURIComponent(code)}&segment=${segment}`,{method:'POST',headers:{'content-type':'audio/wav'},body:wavBlob(parts,sampleRate)});const body=await result.json().catch(()=>({}));if(!result.ok)throw new Error(body.error||'Narration segment could not be stored.');segment+=1;parts=[];samples=0;};while(cursor<sentences.length){const start=cursor;let text='';while(cursor<sentences.length&&text.length<360){const next=sentences[cursor].text;if(text&&text.length+next.length>520)break;text+=`${text?' ':''}${next}`;cursor+=1;}report(`Kokoro · rendering ${Math.round(start/sentences.length*100)}% · segment ${segment+1}`);const output=await this.kokoroAudio(text,selected,1);sampleRate=Number(output.sampling_rate||24000);parts.push(output.audio as Float32Array);samples+=output.audio.length;if(samples/sampleRate>=300)await upload();}await upload();report(`Kokoro narration ready · ${segment} ${segment===1?'segment':'segments'}`);return segment;}
  kokoroChunk(start:number,_single=false){if(start>=this.sentences.length)return null;let next=start;const parts:Sentence[]=[];let length=0;while(next<this.sentences.length){const sentence=this.sentences[next];if(parts.length&&length>=180)break;if(parts.length&&length+sentence.text.length>360)break;parts.push(sentence);length+=sentence.text.length+1;next+=1;}const first=parts[0],last=parts.at(-1)!;return{sentence:{raw:this.source.slice(first.start,last.end),text:parts.map((item)=>item.text).join(' '),start:first.start,end:last.end},next};}
  scheduleKokoro(output:any,chunk:NonNullable<ReturnType<ReadAloudController['kokoroChunk']>>,sentenceIndex:number){if(!this.audioContext){const Context=window.AudioContext||(window as any).webkitAudioContext;if(!Context)throw new Error('AudioContext is not available.');this.audioContext=new Context({latencyHint:'playback'});this.scheduledUntil=this.audioContext.currentTime+.12;}const context=this.audioContext;const samples=output.audio as Float32Array;const rate=Number(output.sampling_rate||24000);const buffer=context.createBuffer(1,samples.length,rate);buffer.copyToChannel(samples as Float32Array<ArrayBuffer>,0);const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);const start=Math.max(this.scheduledUntil,context.currentTime+.06);const end=start+buffer.duration;this.scheduledUntil=end;this.audioTimeline.push({start,end,sentence:chunk.sentence,index:sentenceIndex});this.audioSources.add(source);source.onended=()=>this.audioSources.delete(source);source.start(start);return new Promise<void>((resolve)=>{source.addEventListener('ended',()=>resolve(),{once:true});});}
  startKokoroTimeline(token:number){window.clearInterval(this.audioTimelineTimer);let shown=-1;this.audioTimelineTimer=window.setInterval(()=>{const context=this.audioContext;if(!context||token!==this.token)return;const active=this.audioTimeline.findIndex((item)=>context.currentTime>=item.start&&context.currentTime<item.end);if(active>=0&&active!==shown){shown=active;const item=this.audioTimeline[active];this.index=item.index;this.showSentence(item.sentence);}},80);}
  async runKokoro(token:number){const settings=readSettings();const code=languageCode(this.mount?.language||navigator.language);let voice=settings.voice;const voiceCode=voice.startsWith('e')?'es':voice.startsWith('a')||voice.startsWith('b')?'en':'';if(!KOKORO_VOICES.some((item)=>item.id===voice)||(['es','en'].includes(code)&&voiceCode!==code))voice=code==='es'?'ef_dora':'af_heart';this.state='loading';this.paintButton();this.mount?.report(`Kokoro · buffering audio · ${code}`,'saving');let cursor=this.index;const buffered:Array<{chunk:NonNullable<ReturnType<ReadAloudController['kokoroChunk']>>;output:any;index:number}>=[];let bufferedSeconds=0;while(cursor<this.sentences.length&&(buffered.length<2||bufferedSeconds<10)&&buffered.length<3&&token===this.token){const chunk=this.kokoroChunk(cursor);if(!chunk)break;const output=await this.kokoroAudio(chunk.sentence.text,voice,settings.rate);buffered.push({chunk,output,index:cursor});bufferedSeconds+=output.audio.length/Number(output.sampling_rate||24000);cursor=chunk.next;}if(token!==this.token)return;this.state='reading';this.paintButton();this.mount?.report(`Kokoro · ${bufferedSeconds.toFixed(1)} seconds buffered`,'saving');const endings=buffered.map((item)=>this.scheduleKokoro(item.output,item.chunk,item.index));this.startKokoroTimeline(token);await this.audioContext?.resume();while(cursor<this.sentences.length&&token===this.token){const chunk=this.kokoroChunk(cursor);if(!chunk)break;const output=await this.kokoroAudio(chunk.sentence.text,voice,settings.rate);if(token!==this.token)return;endings.push(this.scheduleKokoro(output,chunk,cursor));cursor=chunk.next;this.mount?.report(`Kokoro · reading · ${Math.max(0,this.scheduledUntil-(this.audioContext?.currentTime||0)).toFixed(1)} seconds ahead`,'saving');}await endings.at(-1);if(token===this.token){this.index=cursor;this.finish();}}
  finish(){this.activeEngine=null;this.state='idle';this.current=null;this.clearHighlight();this.paintButton();this.mount?.report('reading complete');}
  showSentence(sentence:Sentence){this.current=sentence;if(!this.mount)return;this.clearHighlight();const caption=document.createElement('div');caption.className='read-aloud-caption';caption.innerHTML='<i aria-hidden="true">▶</i><mark></mark><small>M · mark</small>';caption.querySelector('mark')!.textContent=sentence.text;this.mount.container.appendChild(caption);const pre=this.mount.container.querySelector('pre');const css=(CSS as any).highlights;if(pre&&css&&typeof (window as any).Highlight==='function'){const walker=document.createTreeWalker(pre,NodeFilter.SHOW_TEXT);let node:Node|null;while(node=walker.nextNode()){const index=(node.textContent||'').indexOf(sentence.raw.trim());if(index>=0){const range=document.createRange();range.setStart(node,index);range.setEnd(node,index+sentence.raw.trim().length);css.set('seshat-read-aloud',new (window as any).Highlight(range));break;}}}const words=new Set(cleanSpeech(sentence.raw).toLowerCase().split(/\s+/).filter((word)=>word.length>3));this.mount.container.querySelectorAll<HTMLElement>('.textLayer span').forEach((span)=>{const text=cleanSpeech(span.textContent||'').toLowerCase();if(text&&[...words].some((word)=>text.includes(word)))span.classList.add('read-aloud-active');});}
  clearHighlight(){document.querySelectorAll('.read-aloud-caption').forEach((item)=>item.remove());document.querySelectorAll('.read-aloud-active').forEach((item)=>item.classList.remove('read-aloud-active'));(CSS as any).highlights?.delete?.('seshat-read-aloud');}
  async mark(){if(!this.mount||!this.current)return;const sentence=this.current;const response=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/annotations`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({quote:sentence.raw.trim(),startOffset:sentence.start,endOffset:sentence.end,sourceKind:'markdown',rects:[],color:'#ffd400',category:'misc',noteType:'reading-mark',locator:`sentence ${this.index+1}`,reviewStatus:'reading'})});if(!response.ok){const result=await response.json().catch(()=>({}));this.mount.report(result.error||'Reading mark could not be saved','error');return;}this.mount.container.querySelector('.read-aloud-caption')?.classList.add('is-marked');window.dispatchEvent(new CustomEvent('seshat:annotations-changed',{detail:{referenceId:this.mount.referenceId}}));this.mount.report(`reading mark saved · sentence ${this.index+1}`);}
  openVoices(){
    if(!this.mount)return;this.dialog?.close();const settings=readSettings();
    const dialog=document.createElement('dialog');dialog.className='reader-voice-dialog';this.dialog=dialog;
    const form=document.createElement('form');const header=document.createElement('header');header.innerHTML='<div><small>READ ALOUD</small><strong>Voice and engine</strong></div>';
    const close=document.createElement('button');close.type='button';close.textContent='×';close.onclick=()=>dialog.close();header.appendChild(close);
    const engineLabel=document.createElement('label');engineLabel.textContent='Engine';const engine=document.createElement('select');
    [['native','Browser / Microsoft voices'],['kokoro','Kokoro local · offline after download']].forEach(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;option.selected=settings.engine===value;engine.appendChild(option);});engineLabel.appendChild(engine);
    const voiceLabel=document.createElement('label');voiceLabel.textContent='Voice';const voice=document.createElement('select');voiceLabel.appendChild(voice);
    const rateLabel=document.createElement('label');rateLabel.textContent='Speed';const rate=document.createElement('input');rate.type='range';rate.min='.65';rate.max='1.6';rate.step='.05';rate.value=String(settings.rate);const rateOutput=document.createElement('output');rateOutput.textContent=`${settings.rate.toFixed(2)}×`;rate.oninput=()=>rateOutput.textContent=`${Number(rate.value).toFixed(2)}×`;rateLabel.append(rate,rateOutput);
    const note=document.createElement('p');note.textContent='Browser voices and Kokoro run independently. Test a browser voice here before using it for the document.';
    const footer=document.createElement('footer');const stop=document.createElement('button');stop.type='button';stop.textContent='Stop';stop.onclick=()=>{this.stop();dialog.close();};
    const test=document.createElement('button');test.type='button';test.textContent='Test voice';
    const save=document.createElement('button');save.type='submit';save.className='primary';save.textContent='Use voice';footer.append(stop,test,save);form.append(header,engineLabel,voiceLabel,rateLabel,note,footer);dialog.appendChild(form);
    let nativeVoiceList:SpeechSynthesisVoice[]=[];
    const renderVoices=async()=>{voice.replaceChildren();test.hidden=engine.value!=='native';if(engine.value==='kokoro'){KOKORO_VOICES.forEach((item)=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.label;option.selected=item.id===settings.voice;voice.appendChild(option);});}else{const voices=await this.nativeVoices();nativeVoiceList=voices;const allowed=settings.nativeVoices.length?voices.filter((item)=>settings.nativeVoices.includes(item.name)):voices;allowed.sort((a,b)=>a.lang.localeCompare(b.lang)||a.name.localeCompare(b.name)).forEach((item)=>{const option=document.createElement('option');option.value=item.name;option.textContent=`${item.name} · ${item.lang}${item.localService?' · local':''}`;option.selected=item.name===settings.voice;voice.appendChild(option);});}};
    test.onclick=()=>{const selected=nativeVoiceList.find((item)=>item.name===voice.value);if(!selected){note.textContent='The selected browser voice is no longer available.';return;}if(this.activeEngine==='native')this.stop();note.textContent=`Testing ${selected.name}…`;void browserSpeech.speak({text:normalizeReaderLanguage(selected.lang)==='es'?'Esta es una prueba directa de la voz seleccionada.':'This is a direct test of the selected voice.',voice:selected,language:selected.lang,rate:Number(rate.value),isCurrent:()=>dialog.open,onStart:()=>{note.textContent=`Speaking with ${selected.name} · ${selected.lang}`;}}).then(()=>{if(dialog.open)note.textContent=`Test complete · ${selected.name}`;}).catch((error)=>{if(dialog.open)note.textContent=error instanceof Error?error.message:'Voice test failed';});};
    engine.onchange=()=>void renderVoices();form.onsubmit=(event)=>{event.preventDefault();browserSpeech.stop();const restart=this.state!=='idle';localStorage.setItem(SETTINGS_KEY,JSON.stringify({...settings,engine:engine.value,voice:voice.value,rate:Number(rate.value)}));dialog.close();this.mount?.report(`${engine.value==='kokoro'?'Kokoro':'browser'} voice selected`);if(restart){this.stop();window.setTimeout(()=>void this.start(),0);}};
    dialog.addEventListener('close',()=>{browserSpeech.stop();this.dialog=null;dialog.remove();});(document.fullscreenElement||document.body).appendChild(dialog);void renderVoices();dialog.showModal();
  }
}

export const readAloud=new ReadAloudController();
