import { browserSpeech, browserSpeechChunks, normalizeBrowserSpeechText } from './browser-speech';
import { billableCharacterCount, chirpVoicesForLanguage } from '../lib/chirp';
import { currentPhoneResourceProfile } from '../lib/client-resources';
import {
  applyNarrationStructure,
  deterministicEarconProfile,
  narrationSsml,
  narrationPauseBefore,
  normalizeNarrationStructureSettings,
  silenceSamples,
  synthesizeEarconSamples,
  type NarrationHeading,
  type NarrationSentence,
  type NarrationStructureSettings,
} from '../lib/narration-structure';
import { bestReadingSpanRun, readingPartIndexAtProgress } from '../lib/read-tracking';
import { READER_VOICE_LONG_PRESS_MS, type ReaderPlayFromDetail } from '../lib/reader-controls';

type ReaderEngine = 'native' | 'kokoro' | 'chirp' | 'rendered';
type ReaderState = 'idle' | 'loading' | 'reading' | 'paused';
type Sentence = NarrationSentence;
type ReaderMount = { referenceId:string; language:string; container:HTMLElement; button:HTMLButtonElement; stopButton?:HTMLButtonElement; report:(message:string,tone?:'ready'|'saving'|'error')=>void; chirpEnabled:boolean };
type NarrationProvider='kokoro'|'chirp';
export type NarrationSegment={index:number;url:string;sizeBytes:number;startOffset:number|null;endOffset:number|null};
type SpeechGroup={text:string;startOffset:number;endOffset:number;sentences:Sentence[]};
type ReaderChapter={title:string;offset:number;time:number};
type ReaderSourceDetail={kind?:string;load?:()=>Promise<string>;headings?:()=>Promise<NarrationHeading[]>};
type ReaderCaptionPosition={x:number;y:number};
type ReaderCaptionPositions={compact?:ReaderCaptionPosition;regular?:ReaderCaptionPosition};

const SETTINGS_KEY='seshat.read-aloud.v1';
const CAPTION_POSITION_KEY='seshat.read-aloud.position.v1';
const MODEL_ID='onnx-community/Kokoro-82M-v1.0-ONNX';
const readerIcon=(name:'speaker'|'bookmark'|'sectionPrevious'|'sectionNext'|'slower'|'faster'|'play'|'stop'|'drag')=>({
  speaker:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h4l5 4V6L8 10H4Z"/><path d="M16 9.5c1.2 1.4 1.2 3.6 0 5M18.5 7c2.6 2.8 2.6 7.2 0 10"/></svg>',
  bookmark:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 4.5h10v15l-5-3.2-5 3.2v-15Z"/></svg>',
  sectionPrevious:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M16 6 10 12l6 6"/><path d="M8 6v12"/></svg>',
  sectionNext:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="m8 6 6 6-6 6"/><path d="M16 6v12"/></svg>',
  slower:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 12h12"/></svg>',
  faster:'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 12h12M12 6v12"/></svg>',
  play:'<svg viewBox="0 0 24 24" aria-hidden="true"><path class="reader-icon-fill" d="m8 5 11 7-11 7V5Z"/></svg>',
  stop:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect class="reader-icon-fill" x="6" y="6" width="12" height="12" rx="1"/></svg>',
  drag:'<svg viewBox="0 0 24 24" aria-hidden="true"><circle class="reader-icon-fill" cx="9" cy="7" r="1.2"/><circle class="reader-icon-fill" cx="15" cy="7" r="1.2"/><circle class="reader-icon-fill" cx="9" cy="12" r="1.2"/><circle class="reader-icon-fill" cx="15" cy="12" r="1.2"/><circle class="reader-icon-fill" cx="9" cy="17" r="1.2"/><circle class="reader-icon-fill" cx="15" cy="17" r="1.2"/></svg>',
})[name];
export const visibleChapterLabelIndexes=(count:number,maximum:number)=>{
  const total=Math.max(0,Math.floor(count)),limit=Math.max(0,Math.floor(maximum));
  if(!total||!limit)return[];
  if(total<=limit)return Array.from({length:total},(_,index)=>index);
  if(limit===1)return[0];
  return [...new Set(Array.from({length:limit},(_,index)=>Math.round(index*(total-1)/(limit-1))))];
};
export const KOKORO_VOICES=[
  {id:'ef_dora',label:'Dora · español · local'},
  {id:'em_alex',label:'Alex · español · local'},
  {id:'em_santa',label:'Santa · español · local'},
  {id:'af_heart',label:'Heart · English · local'},
  {id:'af_bella',label:'Bella · English · local'},
  {id:'am_michael',label:'Michael · English · local'},
];

type ReaderSettings={engine:ReaderEngine;voice:string;rate:number;nativeVoices:string[];structure:NarrationStructureSettings};
const readSettings=():ReaderSettings=>{try{const stored=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}');return{engine:'native',voice:'',rate:1,nativeVoices:[],...stored,structure:normalizeNarrationStructureSettings(stored.structure)}}catch{return{engine:'native',voice:'',rate:1,nativeVoices:[],structure:normalizeNarrationStructureSettings({})}}};
export const steppedReaderRate=(rate:number,delta:number)=>Math.max(.5,Math.min(3,Math.round((Number(rate||1)+delta)*4)/4));
export const boundedReaderCaptionCenter=(x:number,y:number,boundsWidth:number,boundsHeight:number,panelWidth:number,panelHeight:number,margin=6)=>{
  const width=Math.max(0,boundsWidth),height=Math.max(0,boundsHeight),horizontalRoom=width>=panelWidth+margin*2,verticalRoom=height>=panelHeight+margin*2;
  return{
    x:horizontalRoom?Math.max(panelWidth/2+margin,Math.min(width-panelWidth/2-margin,x)):width/2,
    y:verticalRoom?Math.max(panelHeight/2+margin,Math.min(height-panelHeight/2-margin,y)):height/2,
  };
};
export const normalizeReaderLanguage=(value:string)=>{const normalized=String(value||'').trim().toLowerCase();const aliases:Record<string,string>={spa:'es',spanish:'es','español':'es',castellano:'es',eng:'en',english:'en','inglés':'en',fra:'fr',fre:'fr',french:'fr','français':'fr',francais:'fr',deu:'de',ger:'de',german:'de','alemán':'de',deutsch:'de',ita:'it',italian:'it',italiano:'it',nor:'nb',nob:'nb',norwegian:'nb',norsk:'nb','bokmål':'nb',bokmal:'nb',no:'nb',por:'pt',portuguese:'pt',cat:'ca',catalan:'ca',nld:'nl',dut:'nl',dutch:'nl',lat:'la',latin:'la'};if(aliases[normalized])return aliases[normalized];try{const language=new Intl.Locale(normalized.replace('_','-')).language.toLowerCase();return language==='no'?'nb':language;}catch{return normalized.slice(0,2);}};
const languageCode=normalizeReaderLanguage;
const cleanSpeech=(value:string)=>normalizeBrowserSpeechText(value
  .replace(/^---[\s\S]*?---\s*/,'').replace(/```[\s\S]*?```/g,' ')
  .replace(/(?:^|\n)\s*(?:(?:page|pages|p[áa]g(?:ina)?s?|p[áa]g\.)\s*)?\d+(?:\s*(?:of|de)\s*\d+)?\s*(?=\n|$)/gimu,' ')
  .replace(/!\[[^\]]*\]\([^)]*\)/g,' ').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1')
  .replace(/https?:\/\/\S+/g,' ').replace(/^\s{0,3}(?:#{1,6}|>|[-*+]\s|\d+[.)]\s)/gm,'')
  .replace(/[*_`~]/g,''));

export const readingSentenceIndexForQuote=(sentences:Array<Pick<Sentence,'text'|'start'|'end'>>,detail:ReaderPlayFromDetail)=>{
  const quote=cleanSpeech(detail.quote).toLocaleLowerCase();if(!quote)return-1;
  const words=new Set(quote.split(/\s+/).filter((word)=>word.length>3));let best=-1,bestScore=0;
  sentences.forEach((sentence,index)=>{if(Number.isFinite(detail.sectionStart)&&sentence.end<Number(detail.sectionStart))return;if(Number.isFinite(detail.sectionEnd)&&sentence.start>Number(detail.sectionEnd))return;const candidate=sentence.text.toLocaleLowerCase(),shared=[...words].filter((word)=>candidate.includes(word)).length,exact=candidate.includes(quote)||quote.includes(candidate);const score=(exact?100:0)+shared;if(score>bestScore){bestScore=score;best=index;}});
  return best;
};

const groupedSpeechSegments=(sentences:Sentence[],maxBytes:number,structure:Partial<NarrationStructureSettings>={} )=>{
  const encoder=new TextEncoder(),groups:SpeechGroup[]=[];let current:SpeechGroup|null=null;
  for(let index=0;index<sentences.length;index+=1){const sentence=sentences[index];
    const previous=current?.text||'';const candidate:string=`${previous}${previous?' ':''}${sentence.text}`;
    if(current&&(encoder.encode(candidate).length>maxBytes||narrationPauseBefore(sentences,index,1,structure)>=750)){groups.push(current);current={text:sentence.text,startOffset:sentence.start,endOffset:sentence.end,sentences:[sentence]};}
    else if(current)current={text:candidate,startOffset:current.startOffset,endOffset:sentence.end,sentences:[...current.sentences,sentence]};
    else current={text:sentence.text,startOffset:sentence.start,endOffset:sentence.end,sentences:[sentence]};
  }
  if(current)groups.push(current);return groups;
};
const groupedSpeech=(sentences:Sentence[],maxBytes:number)=>groupedSpeechSegments(sentences,maxBytes).map((group)=>group.text);
export const narrationCharacterCount=(source:string,language='en')=>billableCharacterCount(groupedSpeech(splitReadingSentences(source,language),4000).join(''));
export const renderedTimeForSourceOffset=(segments:NarrationSegment[],durations:number[],sourceLength:number,sourceOffset:number)=>{let before=0;for(let index=0;index<durations.length;index+=1){const duration=Math.max(0,Number(durations[index])||0),segment=segments[index];if(segment&&segment.startOffset!==null&&segment.endOffset!==null&&segment.endOffset>segment.startOffset&&sourceOffset>=segment.startOffset&&sourceOffset<=segment.endOffset){const ratio=(sourceOffset-segment.startOffset)/(segment.endOffset-segment.startOffset);return before+duration*Math.max(0,Math.min(1,ratio));}before+=duration;}const total=durations.reduce((sum,value)=>sum+Math.max(0,Number(value)||0),0);return total*Math.max(0,Math.min(1,sourceOffset/Math.max(1,sourceLength)));};

const wavBlob=(parts:Float32Array[],sampleRate:number)=>{const samples=parts.reduce((sum,item)=>sum+item.length,0);const buffer=new ArrayBuffer(44+samples*2);const view=new DataView(buffer);const text=(offset:number,value:string)=>{for(let index=0;index<value.length;index+=1)view.setUint8(offset+index,value.charCodeAt(index));};text(0,'RIFF');view.setUint32(4,36+samples*2,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,samples*2,true);let offset=44;for(const part of parts)for(const sample of part){const clipped=Math.max(-1,Math.min(1,sample));view.setInt16(offset,clipped<0?clipped*0x8000:clipped*0x7fff,true);offset+=2;}return new Blob([buffer],{type:'audio/wav'});};

export const splitReadingSentences=(source:string,language='en',headings:NarrationHeading[]=[]):Sentence[]=>{
  const lineKey=(value:string)=>value.normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();const counts=new Map<string,number>();for(const line of source.split(/\r?\n|\f/)){const key=lineKey(line);if(key.length>=3&&key.length<=100&&key.split(/\s+/).length<=14&&!/[.!?]$/.test(key))counts.set(key,(counts.get(key)||0)+1);}const runningLines=new Set([...counts].filter(([,count])=>count>=3).map(([line])=>line));
  const segments:Array<{segment:string;index:number}>=[];
  const blocks=[...source.matchAll(/\S(?:[\s\S]*?\S)?(?=(?:\r?\n[ \t]*\r?\n|\f)|$)/g)];
  const segmentBlock=(block:string,offset:number)=>{
    try{const Segmenter=(Intl as any).Segmenter;const segmenter=new Segmenter(language||'en',{granularity:'sentence'});for(const value of segmenter.segment(block))segments.push({segment:value.segment,index:offset+value.index});}
    catch{let cursor=0;for(const segment of block.match(/[^.!?\n]+(?:[.!?]+|\n+|$)/g)||[]){const index=block.indexOf(segment,cursor);segments.push({segment,index:offset+index});cursor=index+segment.length;}}
  };
  for(const block of blocks){const text=block[0],offset=Number(block.index)||0;if(/^\s{0,3}#{1,6}\s+\S/.test(text)&&!/\n/.test(text.trim()))segments.push({segment:text,index:offset});else segmentBlock(text,offset);}
  const plain=segments.map(({segment,index})=>{const withoutRunningHeaders=segment.split(/(\r?\n|\f)/).filter((line)=>!runningLines.has(lineKey(line))).join('');return{raw:segment,text:cleanSpeech(withoutRunningHeaders),start:index,end:index+segment.length};}).filter((item)=>item.text.length>1&&item.text.length<1800);
  return applyNarrationStructure(source,plain,headings);
};

class ReadAloudController{
  state:ReaderState='idle';activeEngine:ReaderEngine|null=null;mount:ReaderMount|null=null;loadedReferenceId='';sourceKind='markdown';sentences:Sentence[]=[];index=0;current:Sentence|null=null;token=0;audio:HTMLAudioElement|null=null;audioSourceRate=1;audioContext:AudioContext|null=null;audioSources=new Set<AudioScheduledSourceNode>();audioTimeline:Array<{start:number;end:number;sentence:Sentence;index:number}>=[];audioTimelineTimer=0;scheduledUntil=0;source='';dialog:HTMLDialogElement|null=null;playTooltip:HTMLButtonElement|null=null;captionResizeObserver:ResizeObserver|null=null;kokoro:any=null;kokoroRendering=false;voiceData=new Map<string,Float32Array>();renderedProvider:NarrationProvider='kokoro';renderedSegments:NarrationSegment[]=[];renderedAudios:HTMLAudioElement[]=[];renderedDurations:number[]=[];renderedTotal=0;renderedElapsed=0;renderedChapters:ReaderChapter[]=[];renderedSeek:number|null=null;renderedInterrupt:(()=>void)|null=null;lastPdfPage=0;requestedPdfPage=0;
  constructor(){if(typeof document==='undefined')return;document.addEventListener('keydown',(event)=>{const target=event.target as HTMLElement|null;if(target?.matches('input,textarea,select,[contenteditable="true"]')||event.metaKey||event.ctrlKey||event.altKey)return;if(event.key.toLowerCase()==='m'&&this.current&&this.state!=='idle'){event.preventDefault();void this.mark();}});}
  attach(mount:ReaderMount){
    if(this.mount&&this.mount.referenceId!==mount.referenceId&&this.state!=='idle')this.stop();this.mount=mount;let timer=0,long=false;
    let startX=0,startY=0;
    const open=(event?:Event)=>{event?.preventDefault();long=true;this.openVoices();};
    const down=(event:PointerEvent)=>{if(event.button!==0)return;long=false;startX=event.clientX;startY=event.clientY;timer=window.setTimeout(()=>open(event),READER_VOICE_LONG_PRESS_MS);};
    const clear=()=>{window.clearTimeout(timer);};
    const move=(event:PointerEvent)=>{if(Math.hypot(event.clientX-startX,event.clientY-startY)>12)clear();};
    const position=(event:PointerEvent)=>{if(event.pointerType==='mouse'&&event.button!==0)return;void this.offerPlayFrom(event,mount);};
    const rendered=(event:Event)=>{const provider=(event as CustomEvent<{provider?:NarrationProvider}>).detail?.provider==='chirp'?'chirp':'kokoro';this.mount=mount;void this.playRendered(provider);};
    const playFromEvent=(event:Event)=>{this.mount=mount;void this.playFromQuote((event as CustomEvent<ReaderPlayFromDetail>).detail);};
    const pageRendered=()=>{if(this.mount?.referenceId===mount.referenceId&&this.current&&this.state!=='idle')window.requestAnimationFrame(()=>this.current&&this.trackPdfSentence(this.current));};
    mount.button.addEventListener('pointerdown',down);mount.button.addEventListener('pointerup',clear);mount.button.addEventListener('pointercancel',clear);mount.button.addEventListener('pointermove',move);
    mount.button.addEventListener('click',(event)=>{if(long){long=false;return;}this.mount=mount;if(event.shiftKey){this.openVoices();return;}void this.toggle();});
    mount.stopButton?.addEventListener('click',()=>{this.mount=mount;this.stop();mount.report('reading stopped');});mount.container.addEventListener('pointerup',position);mount.container.addEventListener('seshat:play-rendered',rendered);mount.container.addEventListener('seshat:reader-play-from',playFromEvent);mount.container.addEventListener('seshat:pdf-page-rendered',pageRendered);
    mount.button.title='Read aloud · Shift-click or hold 2 seconds for voices · M marks the current sentence';this.paintButton();
    return()=>{clear();mount.container.removeEventListener('pointerup',position);mount.container.removeEventListener('seshat:play-rendered',rendered);mount.container.removeEventListener('seshat:reader-play-from',playFromEvent);mount.container.removeEventListener('seshat:pdf-page-rendered',pageRendered);this.playTooltip?.remove();this.playTooltip=null;if(this.mount?.button===mount.button&&this.state==='idle')this.mount=null;};
  }
  paintButton(){if(!this.mount)return;const labels:Record<ReaderState,string>={idle:'Read',loading:'Loading…',reading:'Pause',paused:'Resume'};this.mount.button.textContent=labels[this.state];this.mount.button.dataset.readerState=this.state;if(this.mount.stopButton)this.mount.stopButton.hidden=this.state==='idle';const caption=this.mount.container.querySelector<HTMLElement>('.read-aloud-caption');if(caption){const settings=readSettings();const speed=caption.querySelector<HTMLOutputElement>('[data-reader-speed]');if(speed)speed.value=`${settings.rate.toFixed(2)}×`;const transport=caption.querySelector<HTMLButtonElement>('[data-reader-transport]');if(transport){const stopped=this.state==='idle';transport.innerHTML=readerIcon(stopped?'play':'stop');transport.dataset.transportState=stopped?'play':'stop';transport.ariaLabel=stopped?'Play narration':'Stop narration';transport.title=transport.ariaLabel;}}}
  async toggle(){if(!this.mount||this.state==='loading')return;if(this.state==='reading'){this.pause();return;}if(this.state==='paused'){this.resume();return;}await this.start();}
  async loadText(){
    if(!this.mount)return;
    const changed=this.loadedReferenceId!==this.mount.referenceId,sourceRequest:ReaderSourceDetail={};
    this.mount.container.dispatchEvent(new CustomEvent<ReaderSourceDetail>('seshat:reader-source',{detail:sourceRequest}));
    let nativeError:unknown=null;this.source='';this.sourceKind=sourceRequest.kind||'markdown';
    if(sourceRequest.load)try{this.source=await sourceRequest.load();}catch(error){nativeError=error;}
    if(!this.source){
      const response=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/artifact/markdown`,{cache:'no-store'});
      if(!response.ok)throw nativeError instanceof Error?nativeError:new Error('Extracted text is required before reading aloud.');
      this.source=await response.text();this.sourceKind='markdown';
    }
    let headings:NarrationHeading[]=[];
    if(sourceRequest.headings)headings=await sourceRequest.headings().catch(()=>[]);
    if(!headings.length){
      const structure=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/artifact/structure`,{cache:'no-store'}).then((response)=>response.ok?response.json():null).catch(()=>null);
      headings=(structure?.sections||[]).map((section:any)=>({id:String(section.id||''),title:String(section.title||''),level:Number(section.level||1),kind:String(section.kind||'section')})).filter((section:NarrationHeading)=>section.title);
    }
    this.sentences=splitReadingSentences(this.source,this.mount.language,headings);this.loadedReferenceId=this.mount.referenceId;
    if(changed){this.lastPdfPage=0;this.requestedPdfPage=0;}
    if(!this.sentences.length)throw new Error('No readable sentences were found.');
    this.index=0;
    const annotations=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/annotations`).then((result)=>result.ok?result.json():null).catch(()=>null);
    const mark=(annotations?.annotations||[]).filter((item:any)=>item.noteType==='reading-mark').sort((a:any,b:any)=>String(b.createdAt).localeCompare(String(a.createdAt)))[0];
    if(mark){const next=this.sentences.findIndex((sentence)=>sentence.start>=Number(mark.endOffset||0));if(next>=0)this.index=next;}
  }
  async start(fromIndex?:number){if(!this.mount)return;if(this.state!=='idle')this.stop(false);const stored=readSettings(),settings={...stored,engine:stored.engine==='chirp'&&!this.mount.chirpEnabled?'native':stored.engine} as ReaderSettings;if(settings.engine==='kokoro'&&this.kokoroRendering){this.mount.report('Kokoro is rendering · choose Browser/Microsoft or Chirp for simultaneous reading','error');return;}this.activeEngine=settings.engine;this.state='loading';this.paintButton();this.mount.report('preparing read aloud…','saving');try{await this.loadText();if(Number.isFinite(fromIndex))this.index=Math.max(0,Math.min(this.sentences.length-1,Math.floor(fromIndex!)));const token=++this.token;if(settings.engine==='kokoro')await this.runKokoro(token);else if(settings.engine==='chirp')await this.runChirp(token);else await this.runNative(token);}catch(error){this.activeEngine=null;this.state='idle';this.paintButton();this.mount?.report(error instanceof Error?error.message:'Read aloud failed','error');}}
  async offerPlayFrom(event:PointerEvent,mount:ReaderMount){const target=event.target as HTMLElement|null;if(!target||target.closest('button,a,input,select,textarea,dialog,.read-aloud-caption,.play-from-tooltip'))return;const htmlContent=target.closest<HTMLElement>('.webarchive-reader-content');const textTarget=target.closest<HTMLElement>('pre,.textLayer span')||(htmlContent?target.closest<HTMLElement>('p,h1,h2,h3,h4,h5,h6,li,blockquote,figcaption,td,th')||target:null);if(!textTarget)return;if(window.getSelection()?.toString().trim())return;this.mount=mount;if(this.loadedReferenceId!==mount.referenceId||!this.sentences.length)try{await this.loadText();}catch{return;}let sentenceIndex=-1;const sourceRoot=textTarget.closest<HTMLElement>('pre')||htmlContent;if(sourceRoot){const doc=document as any;const caret=doc.caretPositionFromPoint?.(event.clientX,event.clientY);const rangeAtPoint=caret?null:doc.caretRangeFromPoint?.(event.clientX,event.clientY);const node=caret?.offsetNode||rangeAtPoint?.startContainer,offset=caret?.offset??rangeAtPoint?.startOffset;if(node&&sourceRoot.contains(node)&&Number.isFinite(offset)){const range=document.createRange();range.selectNodeContents(sourceRoot);try{range.setEnd(node,offset);const sourceOffset=range.toString().length;sentenceIndex=this.sentences.findIndex((sentence)=>sourceOffset>=sentence.start&&sourceOffset<=sentence.end);}catch{}}}if(sentenceIndex<0){const clicked=cleanSpeech(textTarget.textContent||'').toLowerCase(),words=new Set(clicked.split(/\s+/).filter((word)=>word.length>3));let best=-1,bestScore=0;this.sentences.forEach((sentence,index)=>{const candidate=sentence.text.toLowerCase();const score=(clicked&&candidate.includes(clicked)?100:0)+[...words].filter((word)=>candidate.includes(word)).length-Math.abs(index-this.index)*.0001;if(score>bestScore){bestScore=score;best=index;}});sentenceIndex=best;}if(sentenceIndex<0)return;this.playTooltip?.remove();const tooltip=document.createElement('button');tooltip.type='button';tooltip.className='play-from-tooltip';tooltip.textContent='Play from here';tooltip.style.left=`${Math.max(8,Math.min(window.innerWidth-132,event.clientX+8))}px`;tooltip.style.top=`${Math.max(8,Math.min(window.innerHeight-42,event.clientY+8))}px`;tooltip.onclick=(click)=>{click.preventDefault();click.stopPropagation();tooltip.remove();if(this.playTooltip===tooltip)this.playTooltip=null;void this.playFrom(sentenceIndex);};this.playTooltip=tooltip;(document.fullscreenElement||document.body).appendChild(tooltip);window.setTimeout(()=>{if(this.playTooltip===tooltip){tooltip.remove();this.playTooltip=null;}},5000);}
  async playFrom(sentenceIndex:number){const target=Math.max(0,Math.min(this.sentences.length-1,Math.floor(sentenceIndex)));if(this.activeEngine==='rendered'&&this.renderedSegments.length&&this.renderedTotal>0){this.index=target;const position=renderedTimeForSourceOffset(this.renderedSegments,this.renderedDurations,this.source.length,this.sentences[target]?.start||0);this.seekRendered(position);this.mount?.report(`playing rendered ${this.renderedProvider} narration from selected text`,'saving');return;}await this.start(target);}
  async playFromQuote(detail:ReaderPlayFromDetail){if(!this.mount||!detail?.quote)return;if(this.loadedReferenceId!==this.mount.referenceId||!this.sentences.length)try{await this.loadText();}catch{return;}const best=readingSentenceIndexForQuote(this.sentences,detail);if(best>=0)await this.playFrom(best);}
  async shiftSection(delta:number){if(!this.mount)return;if(this.loadedReferenceId!==this.mount.referenceId||!this.sentences.length)try{await this.loadText();}catch{return;}const detail:{delta:number;currentOffset?:number;targetOffset?:number}={delta,currentOffset:this.current?.start??this.sentences[this.index]?.start};this.mount.container.dispatchEvent(new CustomEvent('seshat:reader-section-shift',{detail}));if(!Number.isFinite(detail.targetOffset)){this.mount.report('No document sections are available.','error');return;}let target=this.sentences.findIndex((sentence)=>sentence.start>=Number(detail.targetOffset));if(target<0)target=this.sentences.length-1;await this.playFrom(target);}
  pause(){if(this.state!=='reading')return;this.state='paused';if(this.activeEngine==='native')browserSpeech.pause();else this.audio?.pause();void this.audioContext?.suspend();this.paintButton();}
  resume(){if(this.state!=='paused')return;this.state='reading';if(this.activeEngine==='native')browserSpeech.resume();else void this.audio?.play();void this.audioContext?.resume();this.paintButton();}
  adjustRate(delta:number){const settings=readSettings(),next=steppedReaderRate(settings.rate,delta);if(next===settings.rate)return;localStorage.setItem(SETTINGS_KEY,JSON.stringify({...settings,rate:next}));if(this.audio){const playback=this.activeEngine==='chirp'?next/Math.max(.25,this.audioSourceRate):next;this.audio.defaultPlaybackRate=playback;this.audio.playbackRate=playback;}this.paintButton();const deferred=this.state!=='idle'&&!this.audio&&this.activeEngine!=='rendered';this.mount?.report(`reading speed · ${next.toFixed(2)}×${deferred?' · next phrase or audio block':''}`);}
  captionTransport(){if(this.state==='idle'){if(this.renderedSegments.length)void this.playRendered(this.renderedProvider,this.renderedElapsed);else void this.start(this.index);return;}const sentence=this.current,from=this.index;this.stop();if(sentence){this.index=from;this.showSentence(sentence);}this.mount?.report('reading stopped');}
  stop(clear=true){this.token+=1;this.renderedInterrupt?.();this.renderedInterrupt=null;if(this.activeEngine==='native')browserSpeech.stop();else{this.audio?.pause();this.audio=null;this.renderedAudios.forEach((item)=>{item.pause();item.removeAttribute('src');item.load();});this.renderedAudios=[];}window.clearInterval(this.audioTimelineTimer);this.audioTimelineTimer=0;this.audioSources.forEach((source)=>{try{source.stop();}catch{}});this.audioSources.clear();this.audioTimeline=[];this.scheduledUntil=0;if(this.audioContext){void this.audioContext.close();this.audioContext=null;}this.activeEngine=null;this.clearHighlight();this.current=null;this.state='idle';if(clear)this.paintButton();}
  ensureAudioContext(){
    if(!this.audioContext){const Context=window.AudioContext||(window as any).webkitAudioContext;if(!Context)throw new Error('AudioContext is not available.');this.audioContext=new Context({latencyHint:'playback'});}
    return this.audioContext;
  }
  boundaryDurationMs(index:number,rate=readSettings().rate){
    const settings=readSettings(),pause=narrationPauseBefore(this.sentences,index,rate,settings.structure),sentence=this.sentences[index];
    return sentence&&settings.structure.earcons&&sentence.boundaryBefore==='chapter'?Math.max(pause,settings.structure.earconDurationMs):pause;
  }
  scheduleEarcon(index:number,start:number){
    const sentence=this.sentences[index],settings=readSettings();if(!sentence||!settings.structure.earcons||sentence.boundaryBefore!=='chapter'||!this.mount)return start;
    const context=this.ensureAudioContext(),profile=deterministicEarconProfile(this.mount.referenceId,sentence,settings.structure),end=start+profile.durationMs/1000;
    const carrier=context.createOscillator(),modulator=context.createOscillator(),modulation=context.createGain(),level=context.createGain();
    carrier.type='sine';modulator.type='sine';carrier.frequency.setValueAtTime(profile.carrierHz*(profile.direction==='rise'?.88:1.12),start);carrier.frequency.exponentialRampToValueAtTime(profile.carrierHz*(profile.direction==='rise'?1.12:.88),end);
    modulator.frequency.setValueAtTime(profile.modulatorHz,start);modulation.gain.setValueAtTime(profile.carrierHz*profile.modulationIndex*.12,start);
    const fadeIn=Math.min(end,start+profile.fadeInMs/1000),fadeOut=Math.max(fadeIn,end-profile.fadeOutMs/1000);
    level.gain.setValueAtTime(0,start);level.gain.linearRampToValueAtTime(profile.gain,fadeIn);level.gain.setValueAtTime(profile.gain,fadeOut);level.gain.linearRampToValueAtTime(0,end);
    modulator.connect(modulation);modulation.connect(carrier.frequency);carrier.connect(level);level.connect(context.destination);
    this.audioSources.add(carrier);this.audioSources.add(modulator);const remove=()=>{this.audioSources.delete(carrier);this.audioSources.delete(modulator);};carrier.onended=remove;carrier.start(start);modulator.start(start);carrier.stop(end);modulator.stop(end);return end;
  }
  async waitNarration(milliseconds:number,token:number){
    let remaining=Math.max(0,milliseconds),last=performance.now();
    while(remaining>0&&token===this.token){await new Promise((resolve)=>window.setTimeout(resolve,Math.min(50,remaining)));const now=performance.now();if(this.state!=='paused')remaining-=now-last;last=now;}
  }
  async playBoundary(index:number,token:number){
    const duration=this.boundaryDurationMs(index);if(!duration||token!==this.token)return;
    const sentence=this.sentences[index],settings=readSettings();
    if(sentence&&settings.structure.earcons&&sentence.boundaryBefore==='chapter'){
      const context=this.ensureAudioContext();await context.resume();this.scheduleEarcon(index,context.currentTime+.03);
    }
    await this.waitNarration(duration,token);
  }
  renderedBoundarySamples(referenceId:string,sentences:Sentence[],index:number,sampleRate:number){
    const sentence=sentences[index],settings=readSettings(),pause=narrationPauseBefore(sentences,index,1,settings.structure);if(!sentence||!pause)return new Float32Array();
    if(!settings.structure.earcons||sentence.boundaryBefore!=='chapter')return silenceSamples(pause,sampleRate);
    const profile=deterministicEarconProfile(referenceId,sentence,settings.structure),earcon=synthesizeEarconSamples(profile,sampleRate),output=silenceSamples(Math.max(pause,profile.durationMs),sampleRate);output.set(earcon.subarray(0,output.length));return output;
  }
  async speakNative(sentence:Sentence,voice:SpeechSynthesisVoice,language:string,token:number){const chunks=browserSpeechChunks(sentence.text);let started=false;for(const text of chunks){if(token!==this.token)return;await browserSpeech.speak({text,voice,language,rate:readSettings().rate,isCurrent:()=>token===this.token,onStart:()=>{if(!started){started=true;this.showSentence(sentence);}this.mount?.report(`speaking · ${voice.name} · ${voice.lang}`,'saving');}});if(token===this.token)await new Promise((resolve)=>window.setTimeout(resolve,30));}}
  async runNative(token:number){if(!('speechSynthesis'in window))throw new Error('SpeechSynthesis is not available.');const settings=readSettings();const voices=await this.nativeVoices();const language=this.mount?.language||navigator.language;const code=normalizeReaderLanguage(language);const allowed=settings.nativeVoices.length?voices.filter((item)=>settings.nativeVoices.includes(item.name)):voices;const preferred=voices.find((item)=>item.name===settings.voice);const preferredForLanguage=preferred&&allowed.includes(preferred)&&normalizeReaderLanguage(preferred.lang)===code?preferred:null;const voice=preferredForLanguage||allowed.filter((item)=>normalizeReaderLanguage(item.lang)===code).sort((a,b)=>Number(/Microsoft.*Natural/i.test(b.name))-Number(/Microsoft.*Natural/i.test(a.name)))[0]||(preferred&&allowed.includes(preferred)?preferred:null)||allowed[0]||preferred||voices[0];if(!voice)throw new Error('No browser voices are installed.');this.mount?.report(`queued · ${voice.name} · ${voice.lang}`,'saving');this.state='reading';this.paintButton();for(;this.index<this.sentences.length&&token===this.token;this.index+=1){await this.playBoundary(this.index,token);if(token!==this.token)return;const sentence=this.sentences[this.index];await this.speakNative(sentence,voice,language,token);}if(token===this.token)this.finish();}
  async nativeVoices(){return browserSpeech.voices();}
  async loadKokoro(){if(this.kokoro)return this.kokoro;this.mount?.report('downloading Kokoro local model · first use ≈95 MB','saving');const [{KokoroTTS},{env}]=await Promise.all([import('kokoro-js'),import('@huggingface/transformers')]);const wasm=env.backends.onnx.wasm as any;wasm.wasmPaths=undefined;wasm.proxy=true;wasm.numThreads=1;this.kokoro=await KokoroTTS.from_pretrained(MODEL_ID,{dtype:'q8',device:'wasm',progress_callback:(progress:any)=>{if(progress?.status==='progress'&&Number.isFinite(progress.progress))this.mount?.report(`loading Kokoro · ${Math.round(progress.progress)}%`,'saving');}});return this.kokoro;}
  async kokoroAudio(sentence:string,voice:string,rate:number){const tts=await this.loadKokoro();if(!voice.startsWith('e'))return tts.generate(sentence,{voice:voice as any,speed:rate});const [{phonemizeSpanish},{Tensor,RawAudio}]=await Promise.all([import('./spanish-phonemizer'),import('@huggingface/transformers')]);const phonemes=await phonemizeSpanish(sentence);const {input_ids}=tts.tokenizer(phonemes,{truncation:true});let voices=this.voiceData.get(voice);if(!voices){const url=`https://huggingface.co/${MODEL_ID}/resolve/main/voices/${voice}.bin`;const response=await fetch(url);if(!response.ok)throw new Error(`Voice ${voice} could not be downloaded.`);voices=new Float32Array(await response.arrayBuffer());this.voiceData.set(voice,voices);}const offset=256*Math.min(Math.max(Number(input_ids.dims.at(-1))-2,0),509);const style=voices.slice(offset,offset+256);const {waveform}=await tts.model({input_ids,style:new Tensor('float32',style,[1,256]),speed:new Tensor('float32',[rate],[1])});return new RawAudio(waveform.data as Float32Array,24000);}
  async renderNarration(referenceId:string,language:string,voice:string,report:(message:string,progress?:number)=>void){if(this.kokoroRendering)throw new Error('Another Kokoro narration is already rendering.');if(this.activeEngine==='kokoro')throw new Error('Stop live Kokoro reading before rendering; Browser/Microsoft and Chirp may continue.');this.kokoroRendering=true;try{return await this.performKokoroNarration(referenceId,language,voice,report);}finally{this.kokoroRendering=false;}}
  async performKokoroNarration(referenceId:string,language:string,voice:string,report:(message:string,progress?:number)=>void){
    const response=await fetch(`/api/library/${encodeURIComponent(referenceId)}/artifact/markdown`,{cache:'no-store'});if(!response.ok)throw new Error('Extracted text is required before rendering narration.');
    const source=await response.text();const sentences=splitReadingSentences(source,language);if(!sentences.length)throw new Error('No readable sentences were found.');
    const code=languageCode(language||navigator.language);const selected=KOKORO_VOICES.some((item)=>item.id===voice)?voice:code==='es'?'ef_dora':'af_heart';
    const cleared=await fetch(`/api/library/${encodeURIComponent(referenceId)}/narration`,{method:'DELETE'});if(!cleared.ok)throw new Error('Existing narration could not be cleared.');
    let cursor=0,segment=0,parts:Float32Array[]=[],sampleRate=24000,samples=0,progress=0,segmentStart=0,segmentEnd=0;
    const upload=async()=>{if(!parts.length)return;report(`Kokoro · uploading segment ${segment+1}`,progress);const query=new URLSearchParams({voice:selected,language:code,segment:String(segment),startOffset:String(segmentStart),endOffset:String(segmentEnd)});const result=await fetch(`/api/library/${encodeURIComponent(referenceId)}/narration?${query}`,{method:'POST',headers:{'content-type':'audio/wav'},body:wavBlob(parts,sampleRate)});const body=await result.json().catch(()=>({}));if(!result.ok)throw new Error(body.error||'Narration segment could not be stored.');segment+=1;parts=[];samples=0;};
    const chunkAt=(start:number)=>{let next=start,length=0;const group:Sentence[]=[];while(next<sentences.length){if(group.length&&narrationPauseBefore(sentences,next,1,readSettings().structure)>0)break;const sentence=sentences[next];if(group.length&&length>=180)break;if(group.length&&length+sentence.text.length>360)break;group.push(sentence);length+=sentence.text.length+1;next+=1;}return{group,next,text:group.map((item)=>item.text).join(' ')};};
    while(cursor<sentences.length){const start=cursor,chunk=chunkAt(cursor);if(!chunk.group.length)break;cursor=chunk.next;if(!parts.length)segmentStart=sentences[start].start;segmentEnd=sentences[cursor-1].end;progress=Math.round(start/sentences.length*100);report(`Kokoro · rendering ${progress}% · segment ${segment+1}`,progress);const output=await this.kokoroAudio(chunk.text,selected,1);sampleRate=Number(output.sampling_rate||24000);const boundary=this.renderedBoundarySamples(referenceId,sentences,start,sampleRate);if(boundary.length){parts.push(boundary);samples+=boundary.length;}parts.push(output.audio as Float32Array);samples+=output.audio.length;if(samples/sampleRate>=300)await upload();}
    progress=99;await upload();report(`Kokoro narration ready · ${segment} ${segment===1?'segment':'segments'}`,100);return segment;
  }
  async chirpAudio(referenceId:string,text:string,voice:string,rate:number,ssml=''){const response=await fetch(`/api/library/${encodeURIComponent(referenceId)}/chirp`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text,ssml,voice,rate})});if(!response.ok){const result=await response.json().catch(()=>({}));throw new Error(result.error||'Google Chirp could not synthesize this text.');}return{blob:await response.blob(),rate:Number(response.headers.get('x-seshat-tts-rate')||rate||1),used:Number(response.headers.get('x-seshat-tts-used')||0),remaining:Number(response.headers.get('x-seshat-tts-remaining')||0)};}
  async playAudio(blob:Blob,token:number,sourceRate=1,onProgress?:(progress:number)=>void){const url=URL.createObjectURL(blob),audio=new Audio(url);this.audio=audio;this.audioSourceRate=Math.max(.25,sourceRate);const playback=readSettings().rate/this.audioSourceRate;audio.preservesPitch=true;audio.defaultPlaybackRate=playback;audio.playbackRate=playback;await new Promise<void>((resolve,reject)=>{let settled=false;const done=(error?:Error)=>{if(settled)return;settled=true;window.clearInterval(watch);URL.revokeObjectURL(url);if(this.audio===audio){this.audio=null;this.audioSourceRate=1;}error?reject(error):resolve();};const watch=window.setInterval(()=>{if(token!==this.token){audio.pause();audio.removeAttribute('src');done();return;}if(Number.isFinite(audio.duration)&&audio.duration>0)onProgress?.(audio.currentTime/audio.duration);},120);audio.onended=()=>{onProgress?.(1);done();};audio.onerror=()=>done(token===this.token?new Error('Chirp audio could not be played.'):undefined);audio.play().catch((error)=>done(error instanceof Error?error:new Error('Chirp audio could not start.')));});}
  cloudChunk(start:number,single=false){if(start>=this.sentences.length)return null;let next=start;const parts:Sentence[]=[];const encoder=new TextEncoder();while(next<this.sentences.length){if(single&&parts.length)break;if(parts.length&&this.boundaryDurationMs(next)>0)break;const sentence=this.sentences[next],candidate=[...parts,sentence].map((item)=>item.text).join(' ');if(parts.length&&encoder.encode(candidate).length>1200)break;parts.push(sentence);next+=1;if(encoder.encode(candidate).length>=700)break;}const first=parts[0],last=parts.at(-1)!;return{sentence:{...first,raw:this.source.slice(first.start,last.end),text:parts.map((item)=>item.text).join(' '),end:last.end},parts,next};}
  async runChirp(token:number){if(!this.mount)return;const settings=readSettings(),code=languageCode(this.mount.language||navigator.language);const available=chirpVoicesForLanguage(code);const voice=available.find((item)=>item.id===settings.voice)?.id||available[0]?.id;if(!voice)throw new Error(`Google Chirp has no configured voice for ${code}.`);let cursor=this.index,chunk=this.cloudChunk(cursor,true);if(!chunk)return this.finish();this.state='loading';this.paintButton();this.mount.report(`Google Chirp · preparing first phrase · ${code}`,'saving');let pending=this.chirpAudio(this.mount.referenceId,chunk.sentence.text,voice,readSettings().rate);while(chunk&&token===this.token){const audio=await pending;if(token!==this.token)return;const active=chunk,activeIndex=cursor;cursor=active.next;const next=this.cloudChunk(cursor),nextPending=next?this.chirpAudio(this.mount.referenceId,next.sentence.text,voice,readSettings().rate):null;this.state='reading';this.paintButton();await this.playBoundary(activeIndex,token);if(token!==this.token){void nextPending?.catch(()=>undefined);return;}let shown=-1;const track=(progress:number)=>{const part=readingPartIndexAtProgress(active.parts.map((item)=>item.text.length),progress);if(part===shown)return;shown=part;this.index=activeIndex+part;this.showSentence(active.parts[part]);};track(0);this.mount.report(`Google Chirp · reading · ${audio.remaining.toLocaleString()} characters left this month`,'saving');await this.playAudio(audio.blob,token,audio.rate,track);if(token!==this.token){void nextPending?.catch(()=>undefined);return;}chunk=next;if(nextPending)pending=nextPending;}if(token===this.token){this.index=cursor;this.finish();}}
  async narrationAudio(segment:NarrationSegment){const audio=new Audio(segment.url);audio.preload='metadata';await new Promise<void>((resolve,reject)=>{let settled=false;const done=(error?:Error)=>{if(settled)return;settled=true;window.clearTimeout(timeout);audio.onloadedmetadata=null;audio.onerror=null;error?reject(error):resolve();};const timeout=window.setTimeout(()=>done(new Error('Rendered narration metadata timed out.')),20000);audio.onloadedmetadata=()=>done();audio.onerror=()=>done(new Error('Rendered narration could not be loaded.'));audio.load();});return audio;}
  async renderedChapterList(){const structure=await fetch(`/api/library/${encodeURIComponent(this.mount!.referenceId)}/artifact/structure`,{cache:'no-store'}).then((response)=>response.ok?response.json():null).catch(()=>null);const headings:Array<{title:string;offset:number}>=[];for(const section of structure?.sections||[]){if(Number(section.level||1)>2)continue;const title=String(section.title||'').trim();if(!title)continue;const offset=this.source.toLocaleLowerCase().indexOf(title.toLocaleLowerCase());if(offset>=0)headings.push({title,offset});}if(!headings.length){const expression=/^\s{0,3}#{1,2}\s+(.+)$/gm;let match:RegExpExecArray|null;while((match=expression.exec(this.source)))headings.push({title:match[1].trim(),offset:match.index});}return headings.slice(0,80).map((item)=>({...item,time:this.renderedTotal*(item.offset/Math.max(1,this.source.length))}));}
  async playRendered(provider:NarrationProvider='kokoro',startAt?:number){if(!this.mount)return;if(this.activeEngine==='rendered'&&this.renderedProvider===provider&&!Number.isFinite(startAt)){if(this.state==='reading')this.pause();else if(this.state==='paused')this.resume();return;}if(this.state!=='idle')this.stop(false);this.activeEngine='rendered';this.renderedProvider=provider;this.state='loading';this.paintButton();this.mount.report(`loading rendered ${provider} narration…`,'saving');try{await this.loadText();const response=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/narration?provider=${provider}&manifest=1`,{cache:'no-store'});const manifest=await response.json().catch(()=>({}));if(!response.ok||!manifest.segments?.length)throw new Error(manifest.error||'Rendered narration was not found.');this.renderedSegments=manifest.segments;if(currentPhoneResourceProfile()){this.renderedAudios=[];for(const segment of this.renderedSegments)this.renderedAudios.push(await this.narrationAudio(segment));}else this.renderedAudios=await Promise.all(this.renderedSegments.map((segment)=>this.narrationAudio(segment)));this.renderedDurations=this.renderedAudios.map((audio)=>Number.isFinite(audio.duration)?audio.duration:0);this.renderedTotal=this.renderedDurations.reduce((sum,value)=>sum+value,0);if(!this.renderedTotal)throw new Error('Rendered narration duration is unavailable.');this.renderedChapters=await this.renderedChapterList();this.renderedElapsed=Number.isFinite(startAt)?Math.max(0,Math.min(this.renderedTotal,Number(startAt))):this.renderedTotal*(this.sentences[this.index]?.start||0)/Math.max(1,this.source.length);this.renderedSeek=this.renderedElapsed;const token=++this.token;this.state='reading';this.paintButton();this.mount.report(`playing rendered ${provider} narration`,'saving');await this.runRendered(token);}catch(error){if(this.activeEngine==='rendered'){this.activeEngine=null;this.state='idle';this.paintButton();this.mount?.report(error instanceof Error?error.message:'Rendered narration failed','error');}}}
  renderedSegmentAt(position:number){let before=0;for(let index=0;index<this.renderedDurations.length;index+=1){const duration=this.renderedDurations[index];if(position<before+duration||index===this.renderedDurations.length-1)return{index,local:Math.max(0,Math.min(duration-.01,position-before)),before};before+=duration;}return{index:0,local:0,before:0};}
  renderedSentenceAt(segmentIndex:number,local:number,before:number){const segment=this.renderedSegments[segmentIndex],duration=Math.max(.01,this.renderedDurations[segmentIndex]);let offset:number;if(segment.startOffset!==null&&segment.endOffset!==null&&segment.endOffset>segment.startOffset)offset=segment.startOffset+(segment.endOffset-segment.startOffset)*(local/duration);else offset=this.source.length*((before+local)/Math.max(.01,this.renderedTotal));let low=0,high=this.sentences.length-1;while(low<high){const middle=Math.floor((low+high+1)/2);if(this.sentences[middle].start<=offset)low=middle;else high=middle-1;}return low;}
  async playRenderedSegment(segmentIndex:number,local:number,before:number,token:number){const audio=this.renderedAudios[segmentIndex];this.audio=audio;audio.currentTime=local;audio.playbackRate=readSettings().rate;return new Promise<'ended'|'seek'>((resolve,reject)=>{let settled=false;const done=(result:'ended'|'seek',error?:Error)=>{if(settled)return;settled=true;window.clearInterval(updateTimer);audio.onended=null;audio.onerror=null;if(this.renderedInterrupt===interrupt)this.renderedInterrupt=null;error?reject(error):resolve(result);};const update=()=>{if(token!==this.token){done('seek');return;}this.renderedElapsed=Math.min(this.renderedTotal,before+audio.currentTime);const next=this.renderedSentenceAt(segmentIndex,audio.currentTime,before);if(next!==this.index||!this.current){this.index=next;this.showSentence(this.sentences[next]);}this.updateRenderedTimeline();};const interrupt=()=>{audio.pause();done('seek');};this.renderedInterrupt=interrupt;const updateTimer=window.setInterval(update,200);audio.onended=()=>done('ended');audio.onerror=()=>done('ended',new Error('Rendered narration playback failed.'));update();if(this.state!=='paused')void audio.play().catch((error)=>done('ended',error instanceof Error?error:new Error('Rendered narration could not start.')));});}
  async runRendered(token:number){let position=this.renderedSeek??this.renderedElapsed;while(token===this.token&&position<this.renderedTotal){this.renderedSeek=null;const target=this.renderedSegmentAt(position);const result=await this.playRenderedSegment(target.index,target.local,target.before,token);if(token!==this.token)return;if(this.renderedSeek!==null){position=this.renderedSeek;continue;}if(result==='seek')return;position=target.before+this.renderedDurations[target.index];this.renderedElapsed=position;}if(token===this.token)this.finish();}
  seekRendered(position:number){const next=Math.max(0,Math.min(this.renderedTotal,position));this.renderedElapsed=next;this.renderedSeek=next;this.updateRenderedTimeline();this.renderedInterrupt?.();}
  mountRenderedTimeline(caption:HTMLElement){if(!this.renderedTotal)return;const timeline=document.createElement('div');timeline.className='reader-timeline';const elapsed=document.createElement('output');elapsed.dataset.readerElapsed='';const track=document.createElement('div');track.className='reader-timeline-track';const range=document.createElement('input');range.type='range';range.min='0';range.max=String(this.renderedTotal);range.step='.1';range.value=String(this.renderedElapsed);range.setAttribute('aria-label','Narration position');range.oninput=()=>{const value=Number(range.value);elapsed.value=this.readerTime(value);remaining.value=`−${this.readerTime(this.renderedTotal-value)}`;};range.onchange=()=>this.seekRendered(Number(range.value));const chapters=document.createElement('div');chapters.className='reader-chapters';const visibleLabels=new Set(visibleChapterLabelIndexes(this.renderedChapters.length,window.matchMedia('(max-width: 500px)').matches?5:10));let labelRow=0;this.renderedChapters.forEach((chapter,index)=>{const marker=document.createElement('button');marker.type='button';marker.title=`Chapter ${index+1} · ${chapter.title}`;marker.setAttribute('aria-label',marker.title);marker.style.left=`${chapter.time/this.renderedTotal*100}%`;if(visibleLabels.has(index)){marker.textContent=String(index+1);marker.classList.add('has-label');marker.dataset.labelRow=String(labelRow%2);labelRow+=1;}else marker.classList.add('chapter-tick');marker.onclick=()=>this.seekRendered(chapter.time);chapters.appendChild(marker);});track.append(range,chapters);const remaining=document.createElement('output');remaining.dataset.readerRemaining='';timeline.append(elapsed,track,remaining);caption.appendChild(timeline);this.updateRenderedTimeline();}
  readerTime(seconds:number){const value=Math.max(0,Math.floor(seconds||0));const hours=Math.floor(value/3600),minutes=Math.floor(value%3600/60),secs=value%60;return hours?`${hours}:${String(minutes).padStart(2,'0')}:${String(secs).padStart(2,'0')}`:`${minutes}:${String(secs).padStart(2,'0')}`;}
  updateRenderedTimeline(){const caption=this.mount?.container.querySelector<HTMLElement>('.read-aloud-caption');if(!caption)return;const elapsed=caption.querySelector<HTMLOutputElement>('[data-reader-elapsed]'),remaining=caption.querySelector<HTMLOutputElement>('[data-reader-remaining]'),range=caption.querySelector<HTMLInputElement>('.reader-timeline input[type="range"]');if(elapsed)elapsed.value=this.readerTime(this.renderedElapsed);if(remaining)remaining.value=`−${this.readerTime(this.renderedTotal-this.renderedElapsed)}`;if(range)range.value=String(this.renderedElapsed);}
  async renderChirpNarration(referenceId:string,language:string,voice:string,report:(message:string,progress?:number)=>void){
    const response=await fetch(`/api/library/${encodeURIComponent(referenceId)}/artifact/markdown`,{cache:'no-store'});
    if(!response.ok)throw new Error('Extracted text is required before rendering narration.');
    const source=await response.text(),sentences=splitReadingSentences(source,language);if(!sentences.length)throw new Error('No readable sentences were found.');
    const code=languageCode(language||navigator.language),available=chirpVoicesForLanguage(code),selected=available.find((item)=>item.id===voice)?.id||available[0]?.id;
    if(!selected)throw new Error(`Google Chirp has no configured voice for ${code}.`);
    const settings=readSettings(),groups=groupedSpeechSegments(sentences,3000,settings.structure).map((group)=>({...group,ssml:narrationSsml(group.sentences,1,settings.structure)}));
    const required=groups.reduce((sum,group)=>sum+billableCharacterCount(group.ssml),0);
    const statusResponse=await fetch(`/api/library/${encodeURIComponent(referenceId)}/chirp`,{cache:'no-store'}),status=await statusResponse.json().catch(()=>({}));
    if(!statusResponse.ok||!status.configured)throw new Error(status.error||'Google Chirp is not configured.');
    if(required>Number(status.remaining||0))throw new Error(`This narration needs ${required.toLocaleString()} characters; ${Number(status.remaining||0).toLocaleString()} remain until ${new Date(status.renewsAt).toLocaleDateString()}.`);
    const cleared=await fetch(`/api/library/${encodeURIComponent(referenceId)}/narration?provider=chirp`,{method:'DELETE'});if(!cleared.ok)throw new Error('Existing Chirp narration could not be cleared.');
    for(let segment=0;segment<groups.length;segment+=1){
      const progress=Math.round(segment/groups.length*100),group=groups[segment];report(`Google Chirp · rendering ${progress}% · segment ${segment+1}/${groups.length}`,progress);
      const audio=await this.chirpAudio(referenceId,group.text,selected,1,group.ssml);
      const query=new URLSearchParams({provider:'chirp',voice:selected,language:code,segment:String(segment),startOffset:String(group.startOffset),endOffset:String(group.endOffset)});
      const stored=await fetch(`/api/library/${encodeURIComponent(referenceId)}/narration?${query}`,{method:'POST',headers:{'content-type':'audio/ogg; codecs=opus'},body:audio.blob});
      const body=await stored.json().catch(()=>({}));if(!stored.ok)throw new Error(body.error||'Chirp narration segment could not be stored.');
      report(`Google Chirp · ${audio.remaining.toLocaleString()} characters left this month`,Math.round((segment+1)/groups.length*100));
    }
    report(`Google Chirp narration ready · ${groups.length} ${groups.length===1?'segment':'segments'}`,100);return groups.length;
  }
  kokoroChunk(start:number,_single=false){if(start>=this.sentences.length)return null;let next=start;const parts:Sentence[]=[];let length=0;while(next<this.sentences.length){const sentence=this.sentences[next];if(parts.length&&this.boundaryDurationMs(next)>0)break;if(parts.length&&length>=180)break;if(parts.length&&length+sentence.text.length>360)break;parts.push(sentence);length+=sentence.text.length+1;next+=1;}const first=parts[0],last=parts.at(-1)!;return{sentence:{...first,raw:this.source.slice(first.start,last.end),text:parts.map((item)=>item.text).join(' '),end:last.end},parts,next};}
  scheduleKokoro(output:any,chunk:NonNullable<ReturnType<ReadAloudController['kokoroChunk']>>,sentenceIndex:number){const context=this.ensureAudioContext();if(!this.scheduledUntil)this.scheduledUntil=context.currentTime+.12;const samples=output.audio as Float32Array;const rate=Number(output.sampling_rate||24000);const buffer=context.createBuffer(1,samples.length,rate);buffer.copyToChannel(samples as Float32Array<ArrayBuffer>,0);const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);const boundaryStart=Math.max(this.scheduledUntil,context.currentTime+.06),boundaryDuration=this.boundaryDurationMs(sentenceIndex)/1000;this.scheduleEarcon(sentenceIndex,boundaryStart);const start=boundaryStart+boundaryDuration,end=start+buffer.duration;this.scheduledUntil=end;const totalWeight=chunk.parts.reduce((sum,item)=>sum+Math.max(1,item.text.length),0);let partStart=start;chunk.parts.forEach((sentence,offset)=>{const partEnd=offset===chunk.parts.length-1?end:partStart+buffer.duration*Math.max(1,sentence.text.length)/totalWeight;this.audioTimeline.push({start:partStart,end:partEnd,sentence,index:sentenceIndex+offset});partStart=partEnd;});this.audioSources.add(source);source.onended=()=>this.audioSources.delete(source);source.start(start);return new Promise<void>((resolve)=>{source.addEventListener('ended',()=>resolve(),{once:true});});}
  startKokoroTimeline(token:number){window.clearInterval(this.audioTimelineTimer);let shown=-1;this.audioTimelineTimer=window.setInterval(()=>{const context=this.audioContext;if(!context||token!==this.token)return;const active=this.audioTimeline.findIndex((item)=>context.currentTime>=item.start&&context.currentTime<item.end);if(active>=0&&active!==shown){shown=active;const item=this.audioTimeline[active];this.index=item.index;this.showSentence(item.sentence);}},80);}
  async runKokoro(token:number){const settings=readSettings();const code=languageCode(this.mount?.language||navigator.language);let voice=settings.voice;const voiceCode=voice.startsWith('e')?'es':voice.startsWith('a')||voice.startsWith('b')?'en':'';if(!KOKORO_VOICES.some((item)=>item.id===voice)||(['es','en'].includes(code)&&voiceCode!==code))voice=code==='es'?'ef_dora':'af_heart';this.state='loading';this.paintButton();this.mount?.report(`Kokoro · buffering audio · ${code}`,'saving');let cursor=this.index;const buffered:Array<{chunk:NonNullable<ReturnType<ReadAloudController['kokoroChunk']>>;output:any;index:number}>=[];let bufferedSeconds=0;while(cursor<this.sentences.length&&(buffered.length<2||bufferedSeconds<10)&&buffered.length<3&&token===this.token){const chunk=this.kokoroChunk(cursor);if(!chunk)break;const output=await this.kokoroAudio(chunk.sentence.text,voice,readSettings().rate);buffered.push({chunk,output,index:cursor});bufferedSeconds+=output.audio.length/Number(output.sampling_rate||24000);cursor=chunk.next;}if(token!==this.token)return;this.state='reading';this.paintButton();this.mount?.report(`Kokoro · ${bufferedSeconds.toFixed(1)} seconds buffered`,'saving');const endings=buffered.map((item)=>this.scheduleKokoro(item.output,item.chunk,item.index));this.startKokoroTimeline(token);await this.audioContext?.resume();while(cursor<this.sentences.length&&token===this.token){const chunk=this.kokoroChunk(cursor);if(!chunk)break;const output=await this.kokoroAudio(chunk.sentence.text,voice,readSettings().rate);if(token!==this.token)return;endings.push(this.scheduleKokoro(output,chunk,cursor));cursor=chunk.next;this.mount?.report(`Kokoro · reading · ${Math.max(0,this.scheduledUntil-(this.audioContext?.currentTime||0)).toFixed(1)} seconds ahead`,'saving');}await endings.at(-1);if(token===this.token){this.index=cursor;this.finish();}}
  finish(){if(this.activeEngine==='rendered'){this.renderedElapsed=this.renderedTotal;this.renderedAudios.forEach((item)=>{item.pause();item.removeAttribute('src');item.load();});this.renderedAudios=[];this.audio=null;}this.activeEngine=null;this.state='idle';this.current=null;this.clearHighlight();this.paintButton();this.mount?.report('reading complete');}
  captionPositionSlot(){return window.matchMedia('(max-width: 500px)').matches?'compact' as const:'regular' as const;}
  captionPositions(){try{const value=JSON.parse(localStorage.getItem(CAPTION_POSITION_KEY)||'{}');return value&&typeof value==='object'?value as ReaderCaptionPositions:{};}catch{return{};}}
  savedCaptionPosition(){return this.captionPositions()[this.captionPositionSlot()]||null;}
  saveCaptionPosition(position:ReaderCaptionPosition){localStorage.setItem(CAPTION_POSITION_KEY,JSON.stringify({...this.captionPositions(),[this.captionPositionSlot()]:position}));}
  resetCaptionPosition(caption:HTMLElement){
    const positions=this.captionPositions();delete positions[this.captionPositionSlot()];localStorage.setItem(CAPTION_POSITION_KEY,JSON.stringify(positions));
    caption.removeAttribute('data-reader-positioned');caption.style.removeProperty('left');caption.style.removeProperty('top');caption.style.removeProperty('bottom');caption.style.removeProperty('transform');
  }
  positionCaption(caption:HTMLElement,position:ReaderCaptionPosition){
    const container=this.mount?.container;if(!container||!caption.isConnected)return null;
    const bounds=container.getBoundingClientRect(),panel=caption.getBoundingClientRect();
    const center=boundedReaderCaptionCenter(position.x*bounds.width,position.y*bounds.height,bounds.width,bounds.height,panel.width,panel.height);
    caption.dataset.readerPositioned='true';caption.style.left=`${center.x}px`;caption.style.top=`${center.y}px`;caption.style.bottom='auto';caption.style.transform='translate(-50%,-50%)';
    return{x:bounds.width?center.x/bounds.width:.5,y:bounds.height?center.y/bounds.height:.5};
  }
  installCaptionDrag(caption:HTMLElement,handle:HTMLButtonElement){
    const placeSaved=()=>{const saved=this.savedCaptionPosition();if(saved)this.positionCaption(caption,saved);};
    const currentCenter=()=>{
      const container=this.mount?.container;if(!container)return{x:.5,y:.5};
      const bounds=container.getBoundingClientRect(),panel=caption.getBoundingClientRect();
      return{x:panel.left-bounds.left+panel.width/2,y:panel.top-bounds.top+panel.height/2};
    };
    const nudge=(deltaX:number,deltaY:number)=>{
      const container=this.mount?.container;if(!container)return;const bounds=container.getBoundingClientRect(),panel=caption.getBoundingClientRect(),current=currentCenter();
      const center=boundedReaderCaptionCenter(current.x+deltaX,current.y+deltaY,bounds.width,bounds.height,panel.width,panel.height);
      const normalized={x:bounds.width?center.x/bounds.width:.5,y:bounds.height?center.y/bounds.height:.5};this.positionCaption(caption,normalized);this.saveCaptionPosition(normalized);
    };
    handle.addEventListener('dblclick',(event)=>{event.preventDefault();this.resetCaptionPosition(caption);});
    handle.addEventListener('keydown',(event)=>{
      if(event.key==='Home'){event.preventDefault();this.resetCaptionPosition(caption);return;}
      const movement=event.shiftKey?48:16,deltas:Record<string,[number,number]>={ArrowLeft:[-movement,0],ArrowRight:[movement,0],ArrowUp:[0,-movement],ArrowDown:[0,movement]};
      if(deltas[event.key]){event.preventDefault();nudge(...deltas[event.key]);}
    });
    handle.addEventListener('pointerdown',(event)=>{
      if(event.button!==0)return;event.preventDefault();event.stopPropagation();const container=this.mount?.container;if(!container)return;
      const bounds=container.getBoundingClientRect(),panel=caption.getBoundingClientRect(),start=currentCenter(),startX=event.clientX,startY=event.clientY;let moved=false;
      handle.setPointerCapture(event.pointerId);caption.classList.add('is-positioning');
      const move=(moveEvent:PointerEvent)=>{
        if(moveEvent.pointerId!==event.pointerId)return;const center=boundedReaderCaptionCenter(start.x+moveEvent.clientX-startX,start.y+moveEvent.clientY-startY,bounds.width,bounds.height,panel.width,panel.height);
        if(Math.hypot(moveEvent.clientX-startX,moveEvent.clientY-startY)>3)moved=true;
        this.positionCaption(caption,{x:bounds.width?center.x/bounds.width:.5,y:bounds.height?center.y/bounds.height:.5});
      };
      const stop=(stopEvent:PointerEvent)=>{
        if(stopEvent.pointerId!==event.pointerId)return;caption.classList.remove('is-positioning');handle.releasePointerCapture(stopEvent.pointerId);handle.removeEventListener('pointermove',move);handle.removeEventListener('pointerup',stop);handle.removeEventListener('pointercancel',stop);
        if(moved){const center=currentCenter();this.saveCaptionPosition({x:bounds.width?center.x/bounds.width:.5,y:bounds.height?center.y/bounds.height:.5});}
      };
      handle.addEventListener('pointermove',move);handle.addEventListener('pointerup',stop);handle.addEventListener('pointercancel',stop);
    });
    this.captionResizeObserver?.disconnect();this.captionResizeObserver=typeof ResizeObserver==='function'?new ResizeObserver(()=>{if(!caption.isConnected){this.captionResizeObserver?.disconnect();return;}placeSaved();}):null;
    this.captionResizeObserver?.observe(caption);if(this.mount?.container)this.captionResizeObserver?.observe(this.mount.container);window.requestAnimationFrame(placeSaved);
  }
  trackTextSentence(pre:HTMLElement,sentence:Sentence){const css=(CSS as any).highlights;if(!css||typeof (window as any).Highlight!=='function')return;const walker=document.createTreeWalker(pre,NodeFilter.SHOW_TEXT);let node:Node|null;while(node=walker.nextNode()){const text=node.textContent||'';let index=text.indexOf(sentence.raw.trim());if(index<0&&node===pre.firstChild)index=Math.max(0,Math.min(text.length-1,sentence.start));if(index<0)continue;const range=document.createRange();range.setStart(node,index);range.setEnd(node,Math.min(text.length,index+Math.max(1,sentence.raw.trim().length)));css.set('seshat-read-aloud',new (window as any).Highlight(range));const surface=pre.closest<HTMLElement>('.pod-reading-surface');if(surface){const target=range.getBoundingClientRect(),bounds=surface.getBoundingClientRect(),caption=this.mount?.container.querySelector<HTMLElement>('.read-aloud-caption');const lower=bounds.bottom-(caption?.offsetHeight||0)-24;if(target.top<bounds.top+24||target.bottom>lower)surface.scrollBy({top:target.top-bounds.top-bounds.height*.32,behavior:'smooth'});}break;}}
  trackPdfSentence(sentence:Sentence){if(!this.mount)return;this.mount.container.querySelectorAll('.read-aloud-active,.read-aloud-anchor').forEach((item)=>item.classList.remove('read-aloud-active','read-aloud-anchor'));const pages=[...this.mount.container.querySelectorAll<HTMLElement>('.seshat-pdf-page')];if(!pages.length)return;const total=pages.length,estimated=Math.max(1,Math.min(total,Math.floor((sentence.start/Math.max(1,this.source.length))*total)+1));const rendered=pages.filter((page)=>page.classList.contains('rendered'));const candidates=rendered.filter((page)=>{const number=Number(page.dataset.page);return Math.abs(number-estimated)<=2||(this.lastPdfPage>0&&Math.abs(number-this.lastPdfPage)<=1);});let best:{page:HTMLElement;spans:HTMLElement[];start:number;end:number;score:number}|null=null;for(const page of candidates){const spans=[...page.querySelectorAll<HTMLElement>('.textLayer span')],match=bestReadingSpanRun(spans.map((span)=>span.textContent||''),sentence.text);if(match&&(!best||match.score>best.score))best={page,spans,start:match.start,end:match.end,score:match.score};}if(!best){if(this.requestedPdfPage!==estimated){this.requestedPdfPage=estimated;this.mount.container.dispatchEvent(new CustomEvent('seshat:pdf-goto-page',{detail:{page:estimated}}));}return;}const pageNumber=Number(best.page.dataset.page),previous=this.lastPdfPage;for(let index=best.start;index<=best.end;index+=1)best.spans[index]?.classList.add('read-aloud-active');best.spans[best.start]?.classList.add('read-aloud-anchor');this.lastPdfPage=pageNumber;this.requestedPdfPage=pageNumber;if(previous!==pageNumber)this.mount.container.dispatchEvent(new CustomEvent('seshat:pdf-goto-page',{detail:{page:pageNumber}}));else{const target=best.spans[best.start]?.getBoundingClientRect(),viewer=best.page.closest<HTMLElement>('.seshat-pdf-viewer'),bounds=viewer?.getBoundingClientRect(),caption=this.mount.container.querySelector<HTMLElement>('.read-aloud-caption');if(target&&viewer&&bounds){const lower=bounds.bottom-(caption?.offsetHeight||0)-18;if(target.top<bounds.top+18||target.bottom>lower)viewer.scrollBy({top:target.top-bounds.top-bounds.height*.36,behavior:'smooth'});}}}
  showSentence(sentence:Sentence){
    this.current=sentence;if(!this.mount)return;this.clearHighlight();
    const caption=document.createElement('div');caption.className='read-aloud-caption';caption.setAttribute('role','toolbar');caption.setAttribute('aria-label','Read aloud controls');
    const dragHandle=document.createElement('button');dragHandle.type='button';dragHandle.className='caption-drag-handle';dragHandle.innerHTML=readerIcon('drag');dragHandle.title='Move reading controls · double-click or press Home to reset';dragHandle.ariaLabel=dragHandle.title;
    const controls=document.createElement('div');controls.className='read-aloud-caption-controls';const comment=document.createElement('button');comment.type='button';comment.className='caption-comment';comment.innerHTML=readerIcon('bookmark');comment.title='Mark and classify this reading position';comment.ariaLabel=comment.title;let commentTouch=0;comment.addEventListener('pointerup',(event)=>{event.stopPropagation();if(event.pointerType!=='touch'&&event.pointerType!=='pen')return;event.preventDefault();commentTouch=performance.now();void this.mark();});comment.addEventListener('click',(event)=>{event.stopPropagation();if(performance.now()-commentTouch<700)return;void this.mark();});
    const previousSection=document.createElement('button');previousSection.type='button';previousSection.className='caption-section';previousSection.innerHTML=readerIcon('sectionPrevious');previousSection.title='Previous section';previousSection.ariaLabel=previousSection.title;previousSection.onclick=()=>void this.shiftSection(-1);const nextSection=document.createElement('button');nextSection.type='button';nextSection.className='caption-section';nextSection.innerHTML=readerIcon('sectionNext');nextSection.title='Next section';nextSection.ariaLabel=nextSection.title;nextSection.onclick=()=>void this.shiftSection(1);
    const slower=document.createElement('button');slower.type='button';slower.className='caption-speed';slower.innerHTML=readerIcon('slower');slower.title='Decrease reading speed by 0.25';slower.ariaLabel=slower.title;slower.onclick=()=>this.adjustRate(-.25);const speed=document.createElement('output');speed.dataset.readerSpeed='';speed.ariaLabel='Reading speed';speed.value=`${readSettings().rate.toFixed(2)}×`;const faster=document.createElement('button');faster.type='button';faster.className='caption-speed';faster.innerHTML=readerIcon('faster');faster.title='Increase reading speed by 0.25';faster.ariaLabel=faster.title;faster.onclick=()=>this.adjustRate(.25);const transport=document.createElement('button');transport.type='button';transport.className='caption-transport';transport.dataset.readerTransport='';transport.onclick=()=>this.captionTransport();const voices=document.createElement('button');voices.type='button';voices.className='caption-voices';voices.innerHTML='<span aria-hidden="true">V</span>';voices.title='Choose voice and reading engine';voices.ariaLabel=voices.title;voices.onclick=()=>this.openVoices();controls.append(comment,previousSection,nextSection,slower,speed,faster,transport,voices);caption.append(dragHandle,controls);this.mount.container.appendChild(caption);this.installCaptionDrag(caption,dragHandle);this.paintButton();
    const pre=this.mount.container.querySelector<HTMLElement>('pre');if(pre)this.trackTextSentence(pre,sentence);else if(this.mount.container.querySelector('.seshat-epub-shell'))this.mount.container.dispatchEvent(new CustomEvent('seshat:epub-reader-locate',{detail:{text:sentence.text,start:sentence.start,end:sentence.end}}));else if(this.mount.container.querySelector('.seshat-html-reader'))this.mount.container.dispatchEvent(new CustomEvent('seshat:html-reader-locate',{detail:{text:sentence.text,start:sentence.start,end:sentence.end}}));else this.trackPdfSentence(sentence);if(this.activeEngine==='rendered')this.mountRenderedTimeline(caption);
  }
  clearHighlight(){this.captionResizeObserver?.disconnect();this.captionResizeObserver=null;document.querySelectorAll('.read-aloud-caption').forEach((item)=>item.remove());document.querySelectorAll('.read-aloud-active,.read-aloud-anchor').forEach((item)=>item.classList.remove('read-aloud-active','read-aloud-anchor'));this.mount?.container.dispatchEvent(new CustomEvent('seshat:epub-reader-clear'));this.mount?.container.dispatchEvent(new CustomEvent('seshat:html-reader-clear'));(CSS as any).highlights?.delete?.('seshat-read-aloud');}
  async mark(){if(!this.mount||!this.current)return;const sentence=this.current;const response=await fetch(`/api/library/${encodeURIComponent(this.mount.referenceId)}/annotations`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({quote:sentence.raw.trim(),startOffset:sentence.start,endOffset:sentence.end,sourceKind:this.sourceKind,rects:[],color:'#aaaaaa',category:'misc',noteType:'reading-mark',locator:this.sourceKind==='html'?'webarchive-reader':`sentence ${this.index+1}`,reviewStatus:'reading'})});if(!response.ok){const result=await response.json().catch(()=>({}));this.mount.report(result.error||'Reading mark could not be saved','error');return;}this.mount.container.querySelector('.read-aloud-caption')?.classList.add('is-marked');window.dispatchEvent(new CustomEvent('seshat:annotations-changed',{detail:{referenceId:this.mount.referenceId}}));this.mount.report(`reading mark saved · open Annotations to classify it`);}
  openVoices(){
    if(!this.mount)return;this.dialog?.close();const settings=readSettings();
    const dialog=document.createElement('dialog');dialog.className='reader-voice-dialog';this.dialog=dialog;
    const form=document.createElement('form');const header=document.createElement('header');header.innerHTML='<div><small>READ ALOUD</small><strong>Voice and engine</strong></div>';
    const close=document.createElement('button');close.type='button';close.textContent='×';close.onclick=()=>dialog.close();header.appendChild(close);
    const engineLabel=document.createElement('label');engineLabel.textContent='Engine';const engine=document.createElement('select');
    const engines=[['native','Browser / Microsoft voices'],['kokoro','Kokoro local · offline after download']];if(this.mount.chirpEnabled)engines.push(['chirp','Google Chirp 3 HD · monthly quota']);engines.forEach(([value,label])=>{const option=document.createElement('option');option.value=value;option.textContent=label;option.selected=settings.engine===value;engine.appendChild(option);});if(!this.mount.chirpEnabled&&settings.engine==='chirp')engine.value='native';engineLabel.appendChild(engine);
    const voiceLabel=document.createElement('label');voiceLabel.textContent='Voice';const voice=document.createElement('select');voiceLabel.appendChild(voice);
    const rateLabel=document.createElement('label');rateLabel.className='reader-rate-setting';const rateTitle=document.createElement('span');rateTitle.textContent='Speed';const rate=document.createElement('input');rate.type='range';rate.min='.5';rate.max='3';rate.step='.25';rate.value=String(settings.rate);const rateOutput=document.createElement('output');rateOutput.textContent=`${settings.rate.toFixed(2)}×`;rate.oninput=()=>rateOutput.textContent=`${Number(rate.value).toFixed(2)}×`;rateLabel.append(rateTitle,rate,rateOutput);
    const primaryGrid=document.createElement('div');primaryGrid.className='reader-voice-primary-grid';primaryGrid.append(engineLabel,voiceLabel,rateLabel);
    const structure=document.createElement('fieldset');structure.className='reader-structure-settings';const structureLegend=document.createElement('legend');structureLegend.textContent='Structural narration';structure.appendChild(structureLegend);
    const check=(label:string,checked:boolean)=>{const control=document.createElement('label');control.className='reader-structure-check';const input=document.createElement('input');input.type='checkbox';input.checked=checked;const text=document.createElement('span');text.textContent=label;control.append(input,text);structure.appendChild(control);return input;};
    const rangeControl=(label:string,value:number,minimum:number,maximum:number,step:number,suffix:string)=>{const control=document.createElement('label');control.className='reader-structure-range';const text=document.createElement('span');text.textContent=label;const input=document.createElement('input');input.type='range';input.min=String(minimum);input.max=String(maximum);input.step=String(step);input.value=String(value);const output=document.createElement('output');const paint=()=>output.value=`${input.value}${suffix}`;input.oninput=paint;paint();control.append(text,input,output);structure.appendChild(control);return input;};
    const structuralPauses=check('Intelligent structural pauses',settings.structure.structuralPauses),earcons=check('Fixed FM chapter earcons',settings.structure.earcons);
    const paragraphPause=rangeControl('Paragraph pause',settings.structure.paragraphPauseMs,400,550,25,' ms'),titlePause=rangeControl('Before section title',settings.structure.titlePauseMs,750,1000,25,' ms'),chapterPause=rangeControl('Chapter transition',settings.structure.chapterPauseMs,1200,1600,50,' ms');
    const earconDuration=rangeControl('Earcon duration',settings.structure.earconDurationMs,1200,1800,50,' ms'),earconFadeIn=rangeControl('Earcon fade in',settings.structure.earconFadeInMs,350,550,25,' ms'),earconFadeOut=rangeControl('Earcon fade out',settings.structure.earconFadeOutMs,450,700,25,' ms'),earconGain=rangeControl('Earcon level',settings.structure.earconGainDb,-24,-14,1,' dB');
    const note=document.createElement('p');note.textContent='Browser voices, Kokoro, and Google Chirp run independently. Test a browser voice here before using it for the document.';
    const footer=document.createElement('footer');const stop=document.createElement('button');stop.type='button';stop.textContent='Stop';stop.onclick=()=>{this.stop();dialog.close();};
    const test=document.createElement('button');test.type='button';test.textContent='Test voice';
    const save=document.createElement('button');save.type='submit';save.className='primary';save.textContent='Use voice';footer.append(stop,test,save);form.append(header,primaryGrid,structure,note,footer);dialog.appendChild(form);
    let nativeVoiceList:SpeechSynthesisVoice[]=[];
    const renderVoices=async()=>{voice.replaceChildren();test.hidden=engine.value!=='native';if(engine.value==='kokoro'){KOKORO_VOICES.forEach((item)=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.label;option.selected=item.id===settings.voice;voice.appendChild(option);});note.textContent='Kokoro runs locally and remains available offline after its first download.';}else if(engine.value==='chirp'){const code=normalizeReaderLanguage(this.mount?.language||navigator.language);chirpVoicesForLanguage(code).forEach((item)=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.label;option.selected=item.id===settings.voice;voice.appendChild(option);});const result=await fetch(`/api/library/${encodeURIComponent(this.mount!.referenceId)}/chirp`,{cache:'no-store'}).then((response)=>response.json()).catch(()=>null);note.textContent=result?.configured?`Google Chirp · ${Number(result.remaining).toLocaleString()} of ${Number(result.limit).toLocaleString()} characters remain · renews ${new Date(result.renewsAt).toLocaleDateString()}`:'Google Chirp is not configured on this server.';}else{const voices=await this.nativeVoices();nativeVoiceList=voices;const allowed=settings.nativeVoices.length?voices.filter((item)=>settings.nativeVoices.includes(item.name)):voices;allowed.sort((a,b)=>a.lang.localeCompare(b.lang)||a.name.localeCompare(b.name)).forEach((item)=>{const option=document.createElement('option');option.value=item.name;option.textContent=`${item.name} · ${item.lang}${item.localService?' · local':''}`;option.selected=item.name===settings.voice;voice.appendChild(option);});note.textContent='Browser voices are provided by the operating system or browser. Test the selected voice before reading.';}};
    test.onclick=()=>{const selected=nativeVoiceList.find((item)=>item.name===voice.value);if(!selected){note.textContent='The selected browser voice is no longer available.';return;}if(this.activeEngine==='native')this.stop();note.textContent=`Testing ${selected.name}…`;void browserSpeech.speak({text:normalizeReaderLanguage(selected.lang)==='es'?'Esta es una prueba directa de la voz seleccionada.':'This is a direct test of the selected voice.',voice:selected,language:selected.lang,rate:Number(rate.value),isCurrent:()=>dialog.open,onStart:()=>{note.textContent=`Speaking with ${selected.name} · ${selected.lang}`;}}).then(()=>{if(dialog.open)note.textContent=`Test complete · ${selected.name}`;}).catch((error)=>{if(dialog.open)note.textContent=error instanceof Error?error.message:'Voice test failed';});};
    engine.onchange=()=>void renderVoices();form.onsubmit=(event)=>{event.preventDefault();browserSpeech.stop();const restart=this.state!=='idle';const nextStructure=normalizeNarrationStructureSettings({structuralPauses:structuralPauses.checked,earcons:earcons.checked,paragraphPauseMs:Number(paragraphPause.value),titlePauseMs:Number(titlePause.value),chapterPauseMs:Number(chapterPause.value),earconDurationMs:Number(earconDuration.value),earconFadeInMs:Number(earconFadeIn.value),earconFadeOutMs:Number(earconFadeOut.value),earconGainDb:Number(earconGain.value)});localStorage.setItem(SETTINGS_KEY,JSON.stringify({...settings,engine:engine.value,voice:voice.value,rate:Number(rate.value),structure:nextStructure}));dialog.close();const label=engine.value==='kokoro'?'Kokoro':engine.value==='chirp'?'Google Chirp':'browser';this.mount?.report(`${label} voice and structural narration selected`);if(restart){this.stop();window.setTimeout(()=>void this.start(),0);}};
    dialog.addEventListener('close',()=>{browserSpeech.stop();this.dialog=null;dialog.remove();});(document.fullscreenElement||document.body).appendChild(dialog);void renderVoices();dialog.showModal();
  }
}

export const readAloud=new ReadAloudController();
