import { normalizeDoi } from './identifiers.js';
import { normalizeAuthorName, normalizeOpenAlexId, normalizeScholarlyTitle, type OpenAlexCandidate, type OpenAlexResolution, type OpenAlexWork } from './scholarly.js';

export interface OpenAlexCache { get(key:string):Promise<unknown|null>; set(key:string,value:unknown,expiresAt:string):Promise<void> }
export interface OpenAlexClientOptions { baseUrl?:string;mailto?:string;apiKey?:string;timeoutMs?:number;retries?:number;cacheTtlDays?:number;fetch?:typeof globalThis.fetch;cache?:OpenAlexCache }
const inverseAbstract=(index:unknown):string|undefined => { if (!index || typeof index!=='object') return undefined; const words:Array<[number,string]>=[]; for (const [word,positions] of Object.entries(index as Record<string,unknown>)) if (Array.isArray(positions)) positions.forEach((position)=>{if(Number.isInteger(position))words.push([Number(position),word]);}); return words.sort((a,b)=>a[0]-b[0]).map((item)=>item[1]).join(' ')||undefined; };
const id=(value:unknown,kind:string)=>normalizeOpenAlexId(value,kind);
export const parseOpenAlexWork=(raw:any):OpenAlexWork|null => {
  const workId=id(raw?.id,'W'); const title=String(raw?.title || raw?.display_name || '').trim(); if (!workId||!title) return null;
  const institutions=new Map<string,{id:string;name:string}>(); const authors=(Array.isArray(raw.authorships)?raw.authorships:[]).flatMap((authorship:any)=>{const authorId=id(authorship?.author?.id,'A');const name=String(authorship?.author?.display_name||'').trim();if(!authorId||!name)return[];const institutionIds=(Array.isArray(authorship.institutions)?authorship.institutions:[]).flatMap((institution:any)=>{const institutionId=id(institution?.id,'I');const institutionName=String(institution?.display_name||'').trim();if(institutionId&&institutionName)institutions.set(institutionId,{id:institutionId,name:institutionName});return institutionId?[institutionId]:[];});return[{id:authorId,name,institutionIds}];});
  const topics=(Array.isArray(raw.topics)?raw.topics:[]).flatMap((topic:any)=>{const topicId=id(topic?.id,'T');const name=String(topic?.display_name||'').trim();return topicId&&name?[{id:topicId,name,score:Math.max(0,Math.min(1,Number(topic.score)||0)),field:String(topic?.field?.display_name||'')||undefined}]:[];});
  const source=raw?.primary_location?.source; const sourceId=id(source?.id,'S');
  return {id:workId,doi:normalizeDoi(raw?.doi),title,type:typeof raw?.type==='string'?raw.type:undefined,publicationYear:Number.isInteger(raw?.publication_year)?raw.publication_year:undefined,abstract:inverseAbstract(raw?.abstract_inverted_index),citedByCount:Math.max(0,Number(raw?.cited_by_count)||0),authors,topics,venue:sourceId&&source?.display_name?{id:sourceId,name:String(source.display_name)}:undefined,institutions:[...institutions.values()],referencedWorkIds:[...new Set((Array.isArray(raw?.referenced_works)?raw.referenced_works:[]).map((value:unknown)=>id(value,'W')).filter(Boolean))] as string[],relatedWorkIds:[...new Set((Array.isArray(raw?.related_works)?raw.related_works:[]).map((value:unknown)=>id(value,'W')).filter(Boolean))] as string[]};
};
const sleep=(milliseconds:number)=>new Promise((resolve)=>setTimeout(resolve,milliseconds));
export class OpenAlexClient {
  readonly configured:boolean; private baseUrl:string;private mailto:string;private apiKey:string;private timeoutMs:number;private retries:number;private ttlMs:number;private fetcher:typeof globalThis.fetch;private cache?:OpenAlexCache;
  constructor(options:OpenAlexClientOptions={}) {this.baseUrl=(options.baseUrl||'https://api.openalex.org').replace(/\/$/,'');this.mailto=String(options.mailto||'').trim();this.apiKey=String(options.apiKey||'').trim();this.configured=Boolean(this.apiKey);this.timeoutMs=Math.max(1000,options.timeoutMs||12000);this.retries=Math.max(0,Math.min(5,options.retries??3));this.ttlMs=Math.max(1,options.cacheTtlDays??30)*86400000;this.fetcher=options.fetch||globalThis.fetch;this.cache=options.cache;}
  private async request(path:string,params:Record<string,string>={},cacheKey?:string):Promise<any> {if(!this.configured)throw new Error('OPENALEX_API_KEY_REQUIRED');const key=cacheKey||`${path}?${new URLSearchParams(params)}`;const cached=await this.cache?.get(key);if(cached)return cached;const url=new URL(`${this.baseUrl}${path}`);Object.entries(params).forEach(([name,value])=>url.searchParams.set(name,value));url.searchParams.set('api_key',this.apiKey);if(this.mailto)url.searchParams.set('mailto',this.mailto);let last:unknown;for(let attempt=0;attempt<=this.retries;attempt+=1){try{const response=await this.fetcher(url,{headers:{accept:'application/json','user-agent':`Seshat/0.1${this.mailto?` (mailto:${this.mailto})`:''}`},signal:AbortSignal.timeout(this.timeoutMs)});if(response.ok){const data=await response.json();await this.cache?.set(key,data,new Date(Date.now()+this.ttlMs).toISOString());return data;}if(response.status!==429&&response.status<500)throw new Error(`OPENALEX_${response.status}`);const retry=Number(response.headers.get('retry-after'));await sleep(Number.isFinite(retry)&&retry>0?retry*1000:250*2**attempt);last=new Error(`OPENALEX_${response.status}`);}catch(error){last=error;if(attempt<this.retries)await sleep(250*2**attempt);}}throw last instanceof Error?last:new Error('OPENALEX_REQUEST_FAILED');}
  async workById(value:string):Promise<OpenAlexWork|null>{const workId=normalizeOpenAlexId(value,'W');if(!workId)return null;return parseOpenAlexWork(await this.request(`/works/${encodeURIComponent(workId)}`,{},`work:${workId}`));}
  async workByDoi(value:string):Promise<OpenAlexWork|null>{const doi=normalizeDoi(value);if(!doi)return null;const data=await this.request('/works',{filter:`doi:https://doi.org/${doi}`},`doi:${doi}`);return parseOpenAlexWork(data?.results?.[0]);}
  async searchWorks(query:string,year?:number):Promise<OpenAlexWork[]>{const params:Record<string,string>={search:query,'per-page':'10'};if(year)params.filter=`publication_year:${year}`;const data=await this.request('/works',params,`search:${normalizeScholarlyTitle(query)}:${year||''}`);return (Array.isArray(data?.results)?data.results:[]).map(parseOpenAlexWork).filter((value:OpenAlexWork|null):value is OpenAlexWork=>Boolean(value));}
  async worksByIds(values:string[],limit=100):Promise<OpenAlexWork[]>{const ids=[...new Set(values.map((value)=>normalizeOpenAlexId(value,'W')).filter(Boolean))].slice(0,limit) as string[];const works:OpenAlexWork[]=[];for(let offset=0;offset<ids.length;offset+=25){const part=ids.slice(offset,offset+25);const data=await this.request('/works',{filter:`openalex_id:${part.join('|')}`,'per-page':String(part.length)},`works:${part.join('|')}`);works.push(...(Array.isArray(data?.results)?data.results:[]).map(parseOpenAlexWork).filter((value:OpenAlexWork|null):value is OpenAlexWork=>Boolean(value)));}return works;}
  async citingWorks(value:string,limit=50):Promise<OpenAlexWork[]>{const workId=normalizeOpenAlexId(value,'W');if(!workId)return[];const bounded=Math.max(0,Math.min(50,limit));const data=await this.request('/works',{filter:`cites:${workId}`,'per-page':String(bounded)},`citing:${workId}:${bounded}`);return (Array.isArray(data?.results)?data.results:[]).map(parseOpenAlexWork).filter((work:OpenAlexWork|null):work is OpenAlexWork=>Boolean(work));}
  async resolve(input:{doi?:string;openAlexId?:string;title?:string;publicationYear?:number;authors?:string[]}):Promise<OpenAlexResolution>{if(input.doi){const work=await this.workByDoi(input.doi);if(work)return{status:'resolved',work,confidence:1,method:'doi'};}if(input.openAlexId){const work=await this.workById(input.openAlexId);if(work)return{status:'resolved',work,confidence:1,method:'openalex-id'};}if(!input.title)return{status:'unresolved',confidence:0,method:'none'};const normalizedTitle=normalizeScholarlyTitle(input.title);const candidates=await this.searchWorks(input.title,input.publicationYear);const scored=candidates.map((work)=>{const title=normalizeScholarlyTitle(work.title);const titleScore=title===normalizedTitle?1:(title.includes(normalizedTitle)||normalizedTitle.includes(title))?0.88:tokenJaccard(title,normalizedTitle);const yearScore=input.publicationYear&&work.publicationYear?Math.max(0,1-Math.abs(input.publicationYear-work.publicationYear)*.25):.5;const author=normalizeAuthorName(input.authors?.[0]);const authorScore=author?work.authors.some((item)=>normalizeAuthorName(item.name)===author)?1:0:.5;return{work,score:titleScore*.72+yearScore*.18+authorScore*.1};}).sort((a,b)=>b.score-a.score);const mapped:OpenAlexCandidate[]=scored.slice(0,5).map(({work,score})=>({id:work.id,title:work.title,publicationYear:work.publicationYear,firstAuthor:work.authors[0]?.name,doi:work.doi,score}));const best=scored[0],second=scored[1];if(best&&best.score>=.92&&(!second||best.score-second.score>=.08))return{status:'resolved',work:best.work,candidates:mapped,confidence:best.score,method:input.publicationYear?'title-year':'title-author'};return mapped.length?{status:'ambiguous',candidates:mapped,confidence:best?.score||0,method:input.publicationYear?'title-year':'title-author'}:{status:'unresolved',confidence:0,method:'none'};}
}
const tokenJaccard=(left:string,right:string):number=>{const a=new Set(left.split(' ').filter(Boolean)),b=new Set(right.split(' ').filter(Boolean));const shared=[...a].filter((value)=>b.has(value)).length;return shared/(new Set([...a,...b]).size||1);};
